// ============================================
// PataCerta — Breed catalog (editorial seed)
// ============================================
//
// Dados editoriais sobre raças caninas usados pelo simulador
// "encontrar a raça ideal". Inspirados em fontes públicas (FCI, AKC,
// Purina, Wikipedia pt) mas redigidos por nós — sem republicação literal.
//
// Escalas:
//   - Atributos numéricos 1-5 (1 = baixíssimo, 5 = altíssimo)
//   - size: "small" (< 10kg) | "medium" (10-25kg) | "large" (25-45kg) | "giant" (> 45kg)
//   - coatLength: "short" | "medium" | "long"
//   - barkLevel: "low" | "medium" | "high"
//
// Manter ordenado por nameSlug.

export interface BreedSeed {
  nameSlug: string
  namePt: string
  fciGroup: string | null
  origin: string | null
  summaryPt: string
  size: 'small' | 'medium' | 'large' | 'giant'
  weightMinKg: number
  weightMaxKg: number
  lifespanMinYrs: number
  lifespanMaxYrs: number
  coatLength: 'short' | 'medium' | 'long'
  shedding: number
  hypoallergenic: boolean
  energyLevel: number
  exerciseDailyMin: number
  trainability: number
  barkLevel: 'low' | 'medium' | 'high'
  groomingLevel: number
  goodWithKids: number
  goodWithDogs: number
  goodWithStrangers: number
  apartmentFriendly: boolean
  noviceFriendly: boolean
  toleratesAlone: number
  coldTolerance: number
  heatTolerance: number
  imageUrl?: string | null
}

export const BREEDS: BreedSeed[] = [
  {
    nameSlug: 'akita-inu',
    namePt: 'Akita Inu',
    fciGroup: 'Grupo 5 — Spitz e tipo primitivo',
    origin: 'Japão',
    summaryPt:
      'Cão japonês de porte grande, leal e reservado. Forte instinto de guarda e independência — pede dono experiente.',
    size: 'large',
    weightMinKg: 32,
    weightMaxKg: 45,
    lifespanMinYrs: 10,
    lifespanMaxYrs: 13,
    coatLength: 'medium',
    shedding: 5,
    hypoallergenic: false,
    energyLevel: 3,
    exerciseDailyMin: 60,
    trainability: 3,
    barkLevel: 'low',
    groomingLevel: 4,
    goodWithKids: 3,
    goodWithDogs: 2,
    goodWithStrangers: 2,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 3,
    coldTolerance: 5,
    heatTolerance: 2,
  },
  {
    nameSlug: 'beagle',
    namePt: 'Beagle',
    fciGroup: 'Grupo 6 — Cães de corrida e farejadores',
    origin: 'Inglaterra',
    summaryPt:
      'Sabujo de tamanho médio, alegre e curioso. Vocaliza bastante e segue cheiros — bom companheiro de família activa.',
    size: 'medium',
    weightMinKg: 9,
    weightMaxKg: 14,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 15,
    coatLength: 'short',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 60,
    trainability: 3,
    barkLevel: 'high',
    groomingLevel: 2,
    goodWithKids: 5,
    goodWithDogs: 5,
    goodWithStrangers: 4,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 3,
    heatTolerance: 3,
  },
  {
    nameSlug: 'bichon-maltes',
    namePt: 'Bichon Maltês',
    fciGroup: 'Grupo 9 — Cães de companhia',
    origin: 'Mediterrâneo',
    summaryPt:
      'Pequeno, branco e elegante. Pelagem longa que requer escovagem diária. Carinhoso e adapta-se bem a apartamento.',
    size: 'small',
    weightMinKg: 3,
    weightMaxKg: 4,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 15,
    coatLength: 'long',
    shedding: 1,
    hypoallergenic: true,
    energyLevel: 3,
    exerciseDailyMin: 30,
    trainability: 4,
    barkLevel: 'medium',
    groomingLevel: 5,
    goodWithKids: 3,
    goodWithDogs: 4,
    goodWithStrangers: 4,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 3,
    heatTolerance: 3,
  },
  {
    nameSlug: 'border-collie',
    namePt: 'Border Collie',
    fciGroup: 'Grupo 1 — Cães de pastor e boieiros',
    origin: 'Reino Unido',
    summaryPt:
      'Considerada a raça mais inteligente. Energia inesgotável e necessidade absoluta de trabalho mental e físico diário.',
    size: 'medium',
    weightMinKg: 14,
    weightMaxKg: 20,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 15,
    coatLength: 'medium',
    shedding: 4,
    hypoallergenic: false,
    energyLevel: 5,
    exerciseDailyMin: 120,
    trainability: 5,
    barkLevel: 'medium',
    groomingLevel: 3,
    goodWithKids: 4,
    goodWithDogs: 4,
    goodWithStrangers: 3,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 2,
    coldTolerance: 4,
    heatTolerance: 3,
  },
  {
    nameSlug: 'boxer',
    namePt: 'Boxer',
    fciGroup: 'Grupo 2 — Pinscher, Schnauzer, Molossos',
    origin: 'Alemanha',
    summaryPt:
      'Atlético e brincalhão. Excelente com crianças, protector da família. Necessita de exercício regular.',
    size: 'large',
    weightMinKg: 25,
    weightMaxKg: 32,
    lifespanMinYrs: 10,
    lifespanMaxYrs: 12,
    coatLength: 'short',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 90,
    trainability: 4,
    barkLevel: 'medium',
    groomingLevel: 1,
    goodWithKids: 5,
    goodWithDogs: 4,
    goodWithStrangers: 3,
    apartmentFriendly: false,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 2,
    heatTolerance: 2,
  },
  {
    nameSlug: 'bulldog-frances',
    namePt: 'Bulldog Francês',
    fciGroup: 'Grupo 9 — Cães de companhia',
    origin: 'França',
    summaryPt:
      'Pequeno, musculado e afectuoso. Baixa necessidade de exercício, ideal para apartamento. Sensível ao calor.',
    size: 'small',
    weightMinKg: 8,
    weightMaxKg: 14,
    lifespanMinYrs: 10,
    lifespanMaxYrs: 12,
    coatLength: 'short',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 2,
    exerciseDailyMin: 30,
    trainability: 3,
    barkLevel: 'low',
    groomingLevel: 2,
    goodWithKids: 5,
    goodWithDogs: 4,
    goodWithStrangers: 4,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 2,
    heatTolerance: 1,
  },
  {
    nameSlug: 'bulldog-ingles',
    namePt: 'Bulldog Inglês',
    fciGroup: 'Grupo 2 — Pinscher, Schnauzer, Molossos',
    origin: 'Inglaterra',
    summaryPt:
      'Calmo, afectuoso e teimoso. Não requer muito exercício mas tem custos veterinários elevados pela morfologia.',
    size: 'medium',
    weightMinKg: 18,
    weightMaxKg: 25,
    lifespanMinYrs: 8,
    lifespanMaxYrs: 10,
    coatLength: 'short',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 2,
    exerciseDailyMin: 30,
    trainability: 2,
    barkLevel: 'low',
    groomingLevel: 2,
    goodWithKids: 5,
    goodWithDogs: 3,
    goodWithStrangers: 4,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 3,
    coldTolerance: 2,
    heatTolerance: 1,
  },
  {
    nameSlug: 'cao-da-serra-da-estrela',
    namePt: 'Cão da Serra da Estrela',
    fciGroup: 'Grupo 2 — Pinscher, Schnauzer, Molossos',
    origin: 'Portugal',
    summaryPt:
      'Raça portuguesa de montanha. Grande, robusto e protector. Tradicionalmente guardador de rebanhos.',
    size: 'giant',
    weightMinKg: 30,
    weightMaxKg: 50,
    lifespanMinYrs: 10,
    lifespanMaxYrs: 12,
    coatLength: 'long',
    shedding: 4,
    hypoallergenic: false,
    energyLevel: 3,
    exerciseDailyMin: 60,
    trainability: 3,
    barkLevel: 'medium',
    groomingLevel: 3,
    goodWithKids: 4,
    goodWithDogs: 3,
    goodWithStrangers: 2,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 4,
    coldTolerance: 5,
    heatTolerance: 2,
  },
  {
    nameSlug: 'cao-de-agua-portugues',
    namePt: 'Cão de Água Português',
    fciGroup: 'Grupo 8 — Cães de cobro, levantadores e de água',
    origin: 'Portugal',
    summaryPt:
      'Raça portuguesa, pelo encaracolado e quase sem queda. Energético, inteligente e bom companheiro para famílias activas.',
    size: 'medium',
    weightMinKg: 16,
    weightMaxKg: 25,
    lifespanMinYrs: 11,
    lifespanMaxYrs: 14,
    coatLength: 'long',
    shedding: 1,
    hypoallergenic: true,
    energyLevel: 4,
    exerciseDailyMin: 90,
    trainability: 5,
    barkLevel: 'medium',
    groomingLevel: 4,
    goodWithKids: 5,
    goodWithDogs: 4,
    goodWithStrangers: 3,
    apartmentFriendly: false,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 3,
    heatTolerance: 3,
  },
  {
    nameSlug: 'cavalier-king-charles',
    namePt: 'Cavalier King Charles Spaniel',
    fciGroup: 'Grupo 9 — Cães de companhia',
    origin: 'Reino Unido',
    summaryPt:
      'Pequeno spaniel afectuoso. Excelente com crianças e idosos. Adapta-se a apartamentos.',
    size: 'small',
    weightMinKg: 5,
    weightMaxKg: 8,
    lifespanMinYrs: 9,
    lifespanMaxYrs: 14,
    coatLength: 'long',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 3,
    exerciseDailyMin: 45,
    trainability: 4,
    barkLevel: 'low',
    groomingLevel: 4,
    goodWithKids: 5,
    goodWithDogs: 5,
    goodWithStrangers: 5,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 1,
    coldTolerance: 3,
    heatTolerance: 3,
  },
  {
    nameSlug: 'chihuahua',
    namePt: 'Chihuahua',
    fciGroup: 'Grupo 9 — Cães de companhia',
    origin: 'México',
    summaryPt:
      'A raça mais pequena do mundo. Coragem e atitude desproporcionadas ao tamanho. Vocaliza muito.',
    size: 'small',
    weightMinKg: 1.5,
    weightMaxKg: 3,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 18,
    coatLength: 'short',
    shedding: 2,
    hypoallergenic: false,
    energyLevel: 3,
    exerciseDailyMin: 30,
    trainability: 3,
    barkLevel: 'high',
    groomingLevel: 2,
    goodWithKids: 2,
    goodWithDogs: 3,
    goodWithStrangers: 2,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 1,
    heatTolerance: 4,
  },
  {
    nameSlug: 'cocker-spaniel-ingles',
    namePt: 'Cocker Spaniel Inglês',
    fciGroup: 'Grupo 8 — Cães de cobro, levantadores e de água',
    origin: 'Reino Unido',
    summaryPt:
      'Médio, alegre e amigável. Pelagem que requer manutenção. Bom companheiro de família.',
    size: 'medium',
    weightMinKg: 12,
    weightMaxKg: 16,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 15,
    coatLength: 'long',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 60,
    trainability: 4,
    barkLevel: 'medium',
    groomingLevel: 4,
    goodWithKids: 5,
    goodWithDogs: 4,
    goodWithStrangers: 4,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 3,
    heatTolerance: 3,
  },
  {
    nameSlug: 'dalmata',
    namePt: 'Dálmata',
    fciGroup: 'Grupo 6 — Cães de corrida e farejadores',
    origin: 'Croácia',
    summaryPt:
      'Raça atlética com manchas características. Necessita muito exercício diário. Sociável mas reservado com estranhos.',
    size: 'large',
    weightMinKg: 20,
    weightMaxKg: 32,
    lifespanMinYrs: 11,
    lifespanMaxYrs: 13,
    coatLength: 'short',
    shedding: 5,
    hypoallergenic: false,
    energyLevel: 5,
    exerciseDailyMin: 90,
    trainability: 4,
    barkLevel: 'medium',
    groomingLevel: 2,
    goodWithKids: 4,
    goodWithDogs: 3,
    goodWithStrangers: 3,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 3,
    coldTolerance: 3,
    heatTolerance: 3,
  },
  {
    nameSlug: 'dachshund',
    namePt: 'Dachshund (Cão Salsicha)',
    fciGroup: 'Grupo 4 — Dachshunds',
    origin: 'Alemanha',
    summaryPt:
      'Pequeno, alongado e tenaz. Caçador originalmente. Vocaliza e tem tendência a problemas de coluna.',
    size: 'small',
    weightMinKg: 4,
    weightMaxKg: 9,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 16,
    coatLength: 'short',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 3,
    exerciseDailyMin: 45,
    trainability: 3,
    barkLevel: 'high',
    groomingLevel: 2,
    goodWithKids: 3,
    goodWithDogs: 3,
    goodWithStrangers: 3,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 2,
    heatTolerance: 3,
  },
  {
    nameSlug: 'doberman',
    namePt: 'Doberman',
    fciGroup: 'Grupo 2 — Pinscher, Schnauzer, Molossos',
    origin: 'Alemanha',
    summaryPt:
      'Atlético, leal e altamente treinável. Excelente cão de guarda para donos experientes e activos.',
    size: 'large',
    weightMinKg: 27,
    weightMaxKg: 45,
    lifespanMinYrs: 10,
    lifespanMaxYrs: 13,
    coatLength: 'short',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 5,
    exerciseDailyMin: 90,
    trainability: 5,
    barkLevel: 'medium',
    groomingLevel: 1,
    goodWithKids: 4,
    goodWithDogs: 3,
    goodWithStrangers: 2,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 3,
    coldTolerance: 2,
    heatTolerance: 3,
  },
  {
    nameSlug: 'galgo-portugues',
    namePt: 'Podengo Português',
    fciGroup: 'Grupo 5 — Spitz e tipo primitivo',
    origin: 'Portugal',
    summaryPt:
      'Raça portuguesa antiga, ágil e independente. Existe em três tamanhos. Excelente caçador.',
    size: 'medium',
    weightMinKg: 5,
    weightMaxKg: 30,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 15,
    coatLength: 'short',
    shedding: 2,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 60,
    trainability: 3,
    barkLevel: 'medium',
    groomingLevel: 1,
    goodWithKids: 4,
    goodWithDogs: 4,
    goodWithStrangers: 3,
    apartmentFriendly: false,
    noviceFriendly: true,
    toleratesAlone: 3,
    coldTolerance: 3,
    heatTolerance: 4,
  },
  {
    nameSlug: 'golden-retriever',
    namePt: 'Golden Retriever',
    fciGroup: 'Grupo 8 — Cães de cobro, levantadores e de água',
    origin: 'Reino Unido',
    summaryPt:
      'Um dos cães de família mais populares do mundo. Amigável, paciente e treinável. Necessita exercício e companhia.',
    size: 'large',
    weightMinKg: 25,
    weightMaxKg: 34,
    lifespanMinYrs: 10,
    lifespanMaxYrs: 12,
    coatLength: 'long',
    shedding: 5,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 60,
    trainability: 5,
    barkLevel: 'medium',
    groomingLevel: 4,
    goodWithKids: 5,
    goodWithDogs: 5,
    goodWithStrangers: 5,
    apartmentFriendly: false,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 4,
    heatTolerance: 3,
  },
  {
    nameSlug: 'husky-siberiano',
    namePt: 'Husky Siberiano',
    fciGroup: 'Grupo 5 — Spitz e tipo primitivo',
    origin: 'Sibéria',
    summaryPt:
      'Cão de trenó com energia altíssima. Pelagem densa, sofre com calor. Independente e fugitivo se aborrecido.',
    size: 'large',
    weightMinKg: 16,
    weightMaxKg: 27,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 14,
    coatLength: 'medium',
    shedding: 5,
    hypoallergenic: false,
    energyLevel: 5,
    exerciseDailyMin: 120,
    trainability: 2,
    barkLevel: 'medium',
    groomingLevel: 4,
    goodWithKids: 4,
    goodWithDogs: 4,
    goodWithStrangers: 4,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 2,
    coldTolerance: 5,
    heatTolerance: 1,
  },
  {
    nameSlug: 'jack-russell-terrier',
    namePt: 'Jack Russell Terrier',
    fciGroup: 'Grupo 3 — Terriers',
    origin: 'Inglaterra',
    summaryPt:
      'Pequeno terrier cheio de energia e personalidade. Caçador nato, vocaliza e precisa de muito estímulo.',
    size: 'small',
    weightMinKg: 5,
    weightMaxKg: 8,
    lifespanMinYrs: 13,
    lifespanMaxYrs: 16,
    coatLength: 'short',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 5,
    exerciseDailyMin: 60,
    trainability: 4,
    barkLevel: 'high',
    groomingLevel: 2,
    goodWithKids: 3,
    goodWithDogs: 3,
    goodWithStrangers: 3,
    apartmentFriendly: true,
    noviceFriendly: false,
    toleratesAlone: 2,
    coldTolerance: 3,
    heatTolerance: 3,
  },
  {
    nameSlug: 'labrador-retriever',
    namePt: 'Labrador Retriever',
    fciGroup: 'Grupo 8 — Cães de cobro, levantadores e de água',
    origin: 'Canadá',
    summaryPt:
      'Cão de família por excelência. Amigável, brincalhão e treinável. Alta tendência a sobrepeso se sedentário.',
    size: 'large',
    weightMinKg: 25,
    weightMaxKg: 36,
    lifespanMinYrs: 10,
    lifespanMaxYrs: 12,
    coatLength: 'short',
    shedding: 5,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 60,
    trainability: 5,
    barkLevel: 'medium',
    groomingLevel: 2,
    goodWithKids: 5,
    goodWithDogs: 5,
    goodWithStrangers: 5,
    apartmentFriendly: false,
    noviceFriendly: true,
    toleratesAlone: 3,
    coldTolerance: 4,
    heatTolerance: 3,
  },
  {
    nameSlug: 'lulu-da-pomerania',
    namePt: 'Lulu da Pomerânia',
    fciGroup: 'Grupo 5 — Spitz e tipo primitivo',
    origin: 'Alemanha',
    summaryPt:
      'Pequeno spitz com pelagem fofa. Vivaz, vocal e protector. Adequado para apartamento.',
    size: 'small',
    weightMinKg: 1.5,
    weightMaxKg: 3.5,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 16,
    coatLength: 'long',
    shedding: 4,
    hypoallergenic: false,
    energyLevel: 3,
    exerciseDailyMin: 30,
    trainability: 3,
    barkLevel: 'high',
    groomingLevel: 4,
    goodWithKids: 2,
    goodWithDogs: 3,
    goodWithStrangers: 2,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 4,
    heatTolerance: 2,
  },
  {
    nameSlug: 'mastim-napolitano',
    namePt: 'Mastim Napolitano',
    fciGroup: 'Grupo 2 — Pinscher, Schnauzer, Molossos',
    origin: 'Itália',
    summaryPt:
      'Molosso gigante e imponente. Calmo em casa, excelente guardador. Pede dono experiente e espaço.',
    size: 'giant',
    weightMinKg: 50,
    weightMaxKg: 70,
    lifespanMinYrs: 7,
    lifespanMaxYrs: 9,
    coatLength: 'short',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 2,
    exerciseDailyMin: 45,
    trainability: 3,
    barkLevel: 'low',
    groomingLevel: 2,
    goodWithKids: 3,
    goodWithDogs: 2,
    goodWithStrangers: 1,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 4,
    coldTolerance: 3,
    heatTolerance: 2,
  },
  {
    nameSlug: 'pastor-alemao',
    namePt: 'Pastor Alemão',
    fciGroup: 'Grupo 1 — Cães de pastor e boieiros',
    origin: 'Alemanha',
    summaryPt:
      'Versátil, treinável e leal. Usado em trabalho policial e militar. Necessita estímulo mental e exercício.',
    size: 'large',
    weightMinKg: 22,
    weightMaxKg: 40,
    lifespanMinYrs: 9,
    lifespanMaxYrs: 13,
    coatLength: 'medium',
    shedding: 5,
    hypoallergenic: false,
    energyLevel: 5,
    exerciseDailyMin: 90,
    trainability: 5,
    barkLevel: 'medium',
    groomingLevel: 3,
    goodWithKids: 5,
    goodWithDogs: 4,
    goodWithStrangers: 3,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 3,
    coldTolerance: 4,
    heatTolerance: 3,
  },
  {
    nameSlug: 'pastor-australiano',
    namePt: 'Pastor Australiano',
    fciGroup: 'Grupo 1 — Cães de pastor e boieiros',
    origin: 'EUA',
    summaryPt:
      'Cão de pastor enérgico e inteligente. Pelagem média colorida. Pede trabalho diário ou desporto canino.',
    size: 'medium',
    weightMinKg: 16,
    weightMaxKg: 32,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 15,
    coatLength: 'medium',
    shedding: 4,
    hypoallergenic: false,
    energyLevel: 5,
    exerciseDailyMin: 90,
    trainability: 5,
    barkLevel: 'medium',
    groomingLevel: 3,
    goodWithKids: 5,
    goodWithDogs: 4,
    goodWithStrangers: 3,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 2,
    coldTolerance: 4,
    heatTolerance: 3,
  },
  {
    nameSlug: 'pequenino-papillon',
    namePt: 'Papillon',
    fciGroup: 'Grupo 9 — Cães de companhia',
    origin: 'França/Bélgica',
    summaryPt:
      'Pequeno spaniel com orelhas em borboleta. Vivaz, inteligente e treinável. Surpreende em desportos caninos.',
    size: 'small',
    weightMinKg: 3,
    weightMaxKg: 5,
    lifespanMinYrs: 13,
    lifespanMaxYrs: 16,
    coatLength: 'long',
    shedding: 2,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 45,
    trainability: 5,
    barkLevel: 'medium',
    groomingLevel: 3,
    goodWithKids: 3,
    goodWithDogs: 4,
    goodWithStrangers: 3,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 3,
    coldTolerance: 2,
    heatTolerance: 3,
  },
  {
    nameSlug: 'pinscher-miniatura',
    namePt: 'Pinscher Miniatura',
    fciGroup: 'Grupo 2 — Pinscher, Schnauzer, Molossos',
    origin: 'Alemanha',
    summaryPt:
      'Pequeno e cheio de energia. Atrevido apesar do tamanho. Vocaliza e adora estar activo.',
    size: 'small',
    weightMinKg: 4,
    weightMaxKg: 6,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 16,
    coatLength: 'short',
    shedding: 2,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 45,
    trainability: 3,
    barkLevel: 'high',
    groomingLevel: 1,
    goodWithKids: 3,
    goodWithDogs: 3,
    goodWithStrangers: 3,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 2,
    heatTolerance: 3,
  },
  {
    nameSlug: 'poodle-medio',
    namePt: 'Caniche (Poodle)',
    fciGroup: 'Grupo 9 — Cães de companhia',
    origin: 'França',
    summaryPt:
      'Inteligente e elegante, em vários tamanhos (toy, miniatura, médio, grande). Pelagem encaracolada, baixa queda.',
    size: 'medium',
    weightMinKg: 3,
    weightMaxKg: 30,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 15,
    coatLength: 'long',
    shedding: 1,
    hypoallergenic: true,
    energyLevel: 4,
    exerciseDailyMin: 60,
    trainability: 5,
    barkLevel: 'medium',
    groomingLevel: 5,
    goodWithKids: 5,
    goodWithDogs: 4,
    goodWithStrangers: 4,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 3,
    heatTolerance: 3,
  },
  {
    nameSlug: 'pug',
    namePt: 'Pug (Carlin)',
    fciGroup: 'Grupo 9 — Cães de companhia',
    origin: 'China',
    summaryPt:
      'Pequeno braquicéfalo afectuoso e brincalhão. Sensível ao calor pela morfologia da face.',
    size: 'small',
    weightMinKg: 6,
    weightMaxKg: 9,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 15,
    coatLength: 'short',
    shedding: 4,
    hypoallergenic: false,
    energyLevel: 2,
    exerciseDailyMin: 30,
    trainability: 3,
    barkLevel: 'low',
    groomingLevel: 2,
    goodWithKids: 5,
    goodWithDogs: 4,
    goodWithStrangers: 4,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 2,
    heatTolerance: 1,
  },
  {
    nameSlug: 'rafeiro-do-alentejo',
    namePt: 'Rafeiro do Alentejo',
    fciGroup: 'Grupo 2 — Pinscher, Schnauzer, Molossos',
    origin: 'Portugal',
    summaryPt:
      'Raça portuguesa, grande cão de gado. Calmo, territorial e protector. Pede experiência e espaço amplo.',
    size: 'giant',
    weightMinKg: 35,
    weightMaxKg: 55,
    lifespanMinYrs: 10,
    lifespanMaxYrs: 14,
    coatLength: 'medium',
    shedding: 4,
    hypoallergenic: false,
    energyLevel: 2,
    exerciseDailyMin: 60,
    trainability: 3,
    barkLevel: 'medium',
    groomingLevel: 2,
    goodWithKids: 4,
    goodWithDogs: 3,
    goodWithStrangers: 1,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 4,
    coldTolerance: 4,
    heatTolerance: 3,
  },
  {
    nameSlug: 'rottweiler',
    namePt: 'Rottweiler',
    fciGroup: 'Grupo 2 — Pinscher, Schnauzer, Molossos',
    origin: 'Alemanha',
    summaryPt:
      'Robusto, leal e protector. Treinável mas precisa de socialização desde cedo e dono firme.',
    size: 'large',
    weightMinKg: 35,
    weightMaxKg: 60,
    lifespanMinYrs: 8,
    lifespanMaxYrs: 11,
    coatLength: 'short',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 60,
    trainability: 4,
    barkLevel: 'medium',
    groomingLevel: 2,
    goodWithKids: 4,
    goodWithDogs: 2,
    goodWithStrangers: 2,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 3,
    coldTolerance: 3,
    heatTolerance: 3,
  },
  {
    nameSlug: 'samoiedo',
    namePt: 'Samoiedo',
    fciGroup: 'Grupo 5 — Spitz e tipo primitivo',
    origin: 'Sibéria',
    summaryPt: 'Branco e sorridente. Pelagem densa, sofre com calor. Sociável e brincalhão.',
    size: 'large',
    weightMinKg: 16,
    weightMaxKg: 30,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 14,
    coatLength: 'long',
    shedding: 5,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 75,
    trainability: 3,
    barkLevel: 'high',
    groomingLevel: 5,
    goodWithKids: 5,
    goodWithDogs: 4,
    goodWithStrangers: 4,
    apartmentFriendly: false,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 5,
    heatTolerance: 1,
  },
  {
    nameSlug: 'sao-bernardo',
    namePt: 'São Bernardo',
    fciGroup: 'Grupo 2 — Pinscher, Schnauzer, Molossos',
    origin: 'Suíça',
    summaryPt:
      'Gigante gentil, conhecido como cão de salvamento alpino. Calmo e bom com crianças. Esperança de vida curta.',
    size: 'giant',
    weightMinKg: 60,
    weightMaxKg: 90,
    lifespanMinYrs: 8,
    lifespanMaxYrs: 10,
    coatLength: 'long',
    shedding: 4,
    hypoallergenic: false,
    energyLevel: 2,
    exerciseDailyMin: 60,
    trainability: 3,
    barkLevel: 'low',
    groomingLevel: 4,
    goodWithKids: 5,
    goodWithDogs: 4,
    goodWithStrangers: 4,
    apartmentFriendly: false,
    noviceFriendly: true,
    toleratesAlone: 3,
    coldTolerance: 5,
    heatTolerance: 1,
  },
  {
    nameSlug: 'schnauzer-miniatura',
    namePt: 'Schnauzer Miniatura',
    fciGroup: 'Grupo 2 — Pinscher, Schnauzer, Molossos',
    origin: 'Alemanha',
    summaryPt:
      'Pequeno cão robusto com barba característica. Pelagem de baixa queda. Alerta e brincalhão.',
    size: 'small',
    weightMinKg: 5,
    weightMaxKg: 9,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 15,
    coatLength: 'medium',
    shedding: 1,
    hypoallergenic: true,
    energyLevel: 4,
    exerciseDailyMin: 45,
    trainability: 4,
    barkLevel: 'high',
    groomingLevel: 4,
    goodWithKids: 4,
    goodWithDogs: 3,
    goodWithStrangers: 3,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 3,
    heatTolerance: 3,
  },
  {
    nameSlug: 'shar-pei',
    namePt: 'Shar-Pei',
    fciGroup: 'Grupo 2 — Pinscher, Schnauzer, Molossos',
    origin: 'China',
    summaryPt:
      'Reconhecível pelas pregas. Calmo, leal e independente. Cuidados especiais com pele e olhos.',
    size: 'medium',
    weightMinKg: 18,
    weightMaxKg: 30,
    lifespanMinYrs: 8,
    lifespanMaxYrs: 12,
    coatLength: 'short',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 2,
    exerciseDailyMin: 45,
    trainability: 3,
    barkLevel: 'low',
    groomingLevel: 2,
    goodWithKids: 3,
    goodWithDogs: 2,
    goodWithStrangers: 2,
    apartmentFriendly: true,
    noviceFriendly: false,
    toleratesAlone: 4,
    coldTolerance: 3,
    heatTolerance: 2,
  },
  {
    nameSlug: 'shiba-inu',
    namePt: 'Shiba Inu',
    fciGroup: 'Grupo 5 — Spitz e tipo primitivo',
    origin: 'Japão',
    summaryPt:
      'Spitz japonês de tamanho médio. Independente, limpo (lambe-se como um gato) e reservado com estranhos.',
    size: 'medium',
    weightMinKg: 8,
    weightMaxKg: 11,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 16,
    coatLength: 'medium',
    shedding: 4,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 60,
    trainability: 2,
    barkLevel: 'medium',
    groomingLevel: 3,
    goodWithKids: 3,
    goodWithDogs: 2,
    goodWithStrangers: 2,
    apartmentFriendly: true,
    noviceFriendly: false,
    toleratesAlone: 4,
    coldTolerance: 4,
    heatTolerance: 3,
  },
  {
    nameSlug: 'shih-tzu',
    namePt: 'Shih Tzu',
    fciGroup: 'Grupo 9 — Cães de companhia',
    origin: 'Tibete',
    summaryPt:
      'Pequeno cão de companhia com pelagem longa. Afectuoso e adapta-se a apartamento. Pelagem requer cuidados.',
    size: 'small',
    weightMinKg: 4,
    weightMaxKg: 7,
    lifespanMinYrs: 10,
    lifespanMaxYrs: 16,
    coatLength: 'long',
    shedding: 1,
    hypoallergenic: true,
    energyLevel: 2,
    exerciseDailyMin: 30,
    trainability: 3,
    barkLevel: 'low',
    groomingLevel: 5,
    goodWithKids: 4,
    goodWithDogs: 4,
    goodWithStrangers: 4,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 3,
    coldTolerance: 3,
    heatTolerance: 2,
  },
  {
    nameSlug: 'staffordshire-bull-terrier',
    namePt: 'Staffordshire Bull Terrier',
    fciGroup: 'Grupo 3 — Terriers',
    origin: 'Inglaterra',
    summaryPt:
      'Musculado e afectuoso, conhecido como "babysitter". Excelente com crianças. Pede socialização.',
    size: 'medium',
    weightMinKg: 11,
    weightMaxKg: 17,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 14,
    coatLength: 'short',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 60,
    trainability: 4,
    barkLevel: 'medium',
    groomingLevel: 1,
    goodWithKids: 5,
    goodWithDogs: 2,
    goodWithStrangers: 3,
    apartmentFriendly: true,
    noviceFriendly: false,
    toleratesAlone: 3,
    coldTolerance: 3,
    heatTolerance: 3,
  },
  {
    nameSlug: 'weimaraner',
    namePt: 'Weimaraner',
    fciGroup: 'Grupo 7 — Cães de mostra',
    origin: 'Alemanha',
    summaryPt:
      'Cão de caça atlético com pelagem prateada. Energia alta e necessidade de companhia constante.',
    size: 'large',
    weightMinKg: 25,
    weightMaxKg: 40,
    lifespanMinYrs: 10,
    lifespanMaxYrs: 13,
    coatLength: 'short',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 5,
    exerciseDailyMin: 90,
    trainability: 4,
    barkLevel: 'medium',
    groomingLevel: 1,
    goodWithKids: 4,
    goodWithDogs: 3,
    goodWithStrangers: 3,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 1,
    coldTolerance: 2,
    heatTolerance: 3,
  },
  {
    nameSlug: 'yorkshire-terrier',
    namePt: 'Yorkshire Terrier',
    fciGroup: 'Grupo 3 — Terriers',
    origin: 'Inglaterra',
    summaryPt:
      'Pequeno e elegante terrier com pelagem longa e sedosa. Atrevido e vocal. Adequado a apartamento.',
    size: 'small',
    weightMinKg: 2,
    weightMaxKg: 3.5,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 16,
    coatLength: 'long',
    shedding: 1,
    hypoallergenic: true,
    energyLevel: 3,
    exerciseDailyMin: 30,
    trainability: 3,
    barkLevel: 'high',
    groomingLevel: 5,
    goodWithKids: 3,
    goodWithDogs: 3,
    goodWithStrangers: 3,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 2,
    heatTolerance: 3,
  },
  // ─────────────────────────────────────────────────────────────────────
  // Adições com base nos registos LOP/CPC 2025 — todas as raças com mais
  // de 5 nascimentos registados em Portugal em 2025. Mantemos em bloco
  // separado para facilitar futuras actualizações anuais. Nomes seguem a
  // convenção "popular (nome CPC)" quando difere significativamente.
  // ─────────────────────────────────────────────────────────────────────
  {
    nameSlug: 'alaskan-malamute',
    namePt: 'Alaskan Malamute',
    fciGroup: 'Grupo 5 — Spitz e tipo primitivo',
    origin: 'EUA (Alasca)',
    summaryPt:
      'Cão de trenó robusto e amistoso, herdeiro dos cães dos inuit Mahlemiut. Resistente, sociável com a família mas reservado com cães do mesmo sexo.',
    size: 'large',
    weightMinKg: 34,
    weightMaxKg: 39,
    lifespanMinYrs: 10,
    lifespanMaxYrs: 14,
    coatLength: 'long',
    shedding: 5,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 90,
    trainability: 3,
    barkLevel: 'low',
    groomingLevel: 4,
    goodWithKids: 4,
    goodWithDogs: 3,
    goodWithStrangers: 4,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 2,
    coldTolerance: 5,
    heatTolerance: 1,
  },
  {
    nameSlug: 'american-staffordshire-terrier',
    namePt: 'American Staffordshire Terrier',
    fciGroup: 'Grupo 3 — Terriers',
    origin: 'EUA',
    summaryPt:
      'Musculoso, equilibrado e leal. Coragem aliada a um temperamento estável; em mãos experientes é companheiro afectuoso e fiável.',
    size: 'medium',
    weightMinKg: 18,
    weightMaxKg: 30,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 16,
    coatLength: 'short',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 60,
    trainability: 4,
    barkLevel: 'medium',
    groomingLevel: 1,
    goodWithKids: 4,
    goodWithDogs: 2,
    goodWithStrangers: 3,
    apartmentFriendly: true,
    noviceFriendly: false,
    toleratesAlone: 2,
    coldTolerance: 3,
    heatTolerance: 4,
  },
  {
    nameSlug: 'barbado-da-terceira',
    namePt: 'Barbado da Terceira',
    fciGroup: 'Grupo 1 — Cães de pastor (não FCI; reconhecido pelo CPC)',
    origin: 'Portugal (Açores)',
    summaryPt:
      'Pastor açoreano de aspecto barbado, vivo e brincalhão. Ideal para famílias activas; equilibrado, trabalhador e sociável.',
    size: 'medium',
    weightMinKg: 20,
    weightMaxKg: 27,
    lifespanMinYrs: 11,
    lifespanMaxYrs: 14,
    coatLength: 'long',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 75,
    trainability: 4,
    barkLevel: 'medium',
    groomingLevel: 4,
    goodWithKids: 5,
    goodWithDogs: 4,
    goodWithStrangers: 4,
    apartmentFriendly: false,
    noviceFriendly: true,
    toleratesAlone: 3,
    coldTolerance: 4,
    heatTolerance: 3,
  },
  {
    nameSlug: 'basenji',
    namePt: 'Basenji',
    fciGroup: 'Grupo 5 — Spitz e tipo primitivo',
    origin: 'África Central',
    summaryPt:
      'O "cão que não ladra" — emite um yodle peculiar. Independente, limpíssimo (asseio felino) e atlético. Pede tutor paciente.',
    size: 'small',
    weightMinKg: 9.5,
    weightMaxKg: 11,
    lifespanMinYrs: 13,
    lifespanMaxYrs: 16,
    coatLength: 'short',
    shedding: 1,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 60,
    trainability: 2,
    barkLevel: 'low',
    groomingLevel: 1,
    goodWithKids: 3,
    goodWithDogs: 3,
    goodWithStrangers: 2,
    apartmentFriendly: true,
    noviceFriendly: false,
    toleratesAlone: 2,
    coldTolerance: 1,
    heatTolerance: 5,
  },
  {
    nameSlug: 'basset-hound',
    namePt: 'Basset Hound',
    fciGroup: 'Grupo 6 — Cães de corrida e farejadores',
    origin: 'Inglaterra / França',
    summaryPt:
      'Farejador de pernas curtas e olhar melancólico. Tranquilo em casa, teimoso à trela quando segue um cheiro. Excelente companheiro de família.',
    size: 'medium',
    weightMinKg: 23,
    weightMaxKg: 29,
    lifespanMinYrs: 10,
    lifespanMaxYrs: 12,
    coatLength: 'short',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 2,
    exerciseDailyMin: 45,
    trainability: 2,
    barkLevel: 'high',
    groomingLevel: 2,
    goodWithKids: 5,
    goodWithDogs: 4,
    goodWithStrangers: 4,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 3,
    coldTolerance: 3,
    heatTolerance: 3,
  },
  {
    nameSlug: 'bichon-frise',
    namePt: 'Bichon Frisé',
    fciGroup: 'Grupo 9 — Companhia',
    origin: 'França / Bélgica',
    summaryPt:
      'Pequeno cão branco, encaracolado e alegre. Hipoalergénico, afável e adaptável a apartamento. Pede grooming regular.',
    size: 'small',
    weightMinKg: 5,
    weightMaxKg: 8,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 15,
    coatLength: 'long',
    shedding: 1,
    hypoallergenic: true,
    energyLevel: 3,
    exerciseDailyMin: 30,
    trainability: 4,
    barkLevel: 'medium',
    groomingLevel: 5,
    goodWithKids: 5,
    goodWithDogs: 4,
    goodWithStrangers: 4,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 3,
    heatTolerance: 3,
  },
  {
    nameSlug: 'bichon-havanes',
    namePt: 'Bichon Havanês (Havanese)',
    fciGroup: 'Grupo 9 — Companhia',
    origin: 'Cuba',
    summaryPt:
      'Cão nacional de Cuba, pequeno e festivo. Sociável, hipoalergénico e adapta-se bem a famílias urbanas. Aprende truques com facilidade.',
    size: 'small',
    weightMinKg: 4,
    weightMaxKg: 7.5,
    lifespanMinYrs: 13,
    lifespanMaxYrs: 16,
    coatLength: 'long',
    shedding: 1,
    hypoallergenic: true,
    energyLevel: 3,
    exerciseDailyMin: 30,
    trainability: 4,
    barkLevel: 'medium',
    groomingLevel: 5,
    goodWithKids: 5,
    goodWithDogs: 5,
    goodWithStrangers: 5,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 2,
    heatTolerance: 4,
  },
  {
    nameSlug: 'biewer-terrier',
    namePt: 'Biewer Terrier',
    fciGroup: 'Grupo 3 — Terriers (não FCI; reconhecido por CPC/AKC)',
    origin: 'Alemanha',
    summaryPt:
      'Variante tricolor do Yorkshire desenvolvida nos anos 80. Pequeno, vivo e elegante; afetuoso com a família e excelente para apartamento.',
    size: 'small',
    weightMinKg: 2,
    weightMaxKg: 4,
    lifespanMinYrs: 13,
    lifespanMaxYrs: 16,
    coatLength: 'long',
    shedding: 1,
    hypoallergenic: true,
    energyLevel: 3,
    exerciseDailyMin: 30,
    trainability: 3,
    barkLevel: 'medium',
    groomingLevel: 5,
    goodWithKids: 4,
    goodWithDogs: 3,
    goodWithStrangers: 3,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 2,
    heatTolerance: 3,
  },
  {
    nameSlug: 'boston-terrier',
    namePt: 'Boston Terrier',
    fciGroup: 'Grupo 9 — Companhia',
    origin: 'EUA',
    summaryPt:
      'O "cavalheiro americano" — pequeno, smoking preto e branco, expressão alerta. Sociável, brincalhão e ideal para vida urbana.',
    size: 'small',
    weightMinKg: 4.5,
    weightMaxKg: 11,
    lifespanMinYrs: 11,
    lifespanMaxYrs: 13,
    coatLength: 'short',
    shedding: 2,
    hypoallergenic: false,
    energyLevel: 3,
    exerciseDailyMin: 45,
    trainability: 4,
    barkLevel: 'low',
    groomingLevel: 1,
    goodWithKids: 5,
    goodWithDogs: 4,
    goodWithStrangers: 4,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 2,
    heatTolerance: 2,
  },
  {
    nameSlug: 'braco-alemao-pelo-curto',
    namePt: 'Braco Alemão de Pêlo Curto (Kurzhaar)',
    fciGroup: 'Grupo 7 — Cães de parar',
    origin: 'Alemanha',
    summaryPt:
      'Versátil cão de caça polivalente. Atlético, inteligente e enérgico — pede família activa, exercício diário intenso e treino consistente.',
    size: 'large',
    weightMinKg: 20,
    weightMaxKg: 32,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 14,
    coatLength: 'short',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 5,
    exerciseDailyMin: 120,
    trainability: 4,
    barkLevel: 'medium',
    groomingLevel: 1,
    goodWithKids: 4,
    goodWithDogs: 4,
    goodWithStrangers: 4,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 1,
    coldTolerance: 3,
    heatTolerance: 3,
  },
  {
    nameSlug: 'braco-alemao-pelo-duro',
    namePt: 'Braco Alemão de Pêlo Duro (Drahthaar)',
    fciGroup: 'Grupo 7 — Cães de parar',
    origin: 'Alemanha',
    summaryPt:
      'Variante de pêlo duro do Braco Alemão. Pelagem rústica e impermeável; mesma versatilidade venatória, com mais resistência ao frio.',
    size: 'large',
    weightMinKg: 27,
    weightMaxKg: 32,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 14,
    coatLength: 'medium',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 5,
    exerciseDailyMin: 120,
    trainability: 4,
    barkLevel: 'medium',
    groomingLevel: 2,
    goodWithKids: 4,
    goodWithDogs: 4,
    goodWithStrangers: 3,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 1,
    coldTolerance: 4,
    heatTolerance: 3,
  },
  {
    nameSlug: 'braco-frances-pireneus',
    namePt: 'Braco Francês Tipo Pirinéus',
    fciGroup: 'Grupo 7 — Cães de parar',
    origin: 'França',
    summaryPt:
      'Cão de caça versátil e gentil. Faro excelente e temperamento equilibrado; trabalha em silêncio com fortes qualidades de parar.',
    size: 'medium',
    weightMinKg: 17,
    weightMaxKg: 25,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 14,
    coatLength: 'short',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 90,
    trainability: 4,
    barkLevel: 'low',
    groomingLevel: 1,
    goodWithKids: 4,
    goodWithDogs: 4,
    goodWithStrangers: 4,
    apartmentFriendly: false,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 3,
    heatTolerance: 3,
  },
  {
    nameSlug: 'bull-terrier-miniatura',
    namePt: 'Bull Terrier Miniatura',
    fciGroup: 'Grupo 3 — Terriers',
    origin: 'Inglaterra',
    summaryPt:
      'Versão compacta do Bull Terrier — mesma cabeça em forma de ovo, mesmo carácter brincalhão e teimoso. Excelente companheiro, mau guardião.',
    size: 'small',
    weightMinKg: 11,
    weightMaxKg: 15,
    lifespanMinYrs: 11,
    lifespanMaxYrs: 14,
    coatLength: 'short',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 60,
    trainability: 3,
    barkLevel: 'medium',
    groomingLevel: 1,
    goodWithKids: 4,
    goodWithDogs: 2,
    goodWithStrangers: 3,
    apartmentFriendly: true,
    noviceFriendly: false,
    toleratesAlone: 2,
    coldTolerance: 2,
    heatTolerance: 3,
  },
  {
    nameSlug: 'bull-terrier-standard',
    namePt: 'Bull Terrier',
    fciGroup: 'Grupo 3 — Terriers',
    origin: 'Inglaterra',
    summaryPt:
      'Cabeça oval característica, físico musculado e personalidade exuberante. Brincalhão "criança eterna"; pede limites firmes e socialização cedo.',
    size: 'medium',
    weightMinKg: 22,
    weightMaxKg: 38,
    lifespanMinYrs: 10,
    lifespanMaxYrs: 14,
    coatLength: 'short',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 75,
    trainability: 3,
    barkLevel: 'medium',
    groomingLevel: 1,
    goodWithKids: 4,
    goodWithDogs: 2,
    goodWithStrangers: 3,
    apartmentFriendly: true,
    noviceFriendly: false,
    toleratesAlone: 2,
    coldTolerance: 2,
    heatTolerance: 3,
  },
  {
    nameSlug: 'bullmastiff',
    namePt: 'Bullmastiff',
    fciGroup: 'Grupo 2 — Pinscher e Schnauzer / Molossóides',
    origin: 'Inglaterra',
    summaryPt:
      'Guardião potente e calmo. Imponente sem ser agressivo; afetuoso em casa, intimidante com estranhos. Pede dono firme e socialização desde cedo.',
    size: 'giant',
    weightMinKg: 41,
    weightMaxKg: 59,
    lifespanMinYrs: 7,
    lifespanMaxYrs: 9,
    coatLength: 'short',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 2,
    exerciseDailyMin: 45,
    trainability: 3,
    barkLevel: 'low',
    groomingLevel: 1,
    goodWithKids: 4,
    goodWithDogs: 2,
    goodWithStrangers: 2,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 3,
    coldTolerance: 3,
    heatTolerance: 2,
  },
  {
    nameSlug: 'cane-corso',
    namePt: 'Cane Corso (Cão Corso Italiano)',
    fciGroup: 'Grupo 2 — Pinscher e Schnauzer / Molossóides',
    origin: 'Itália',
    summaryPt:
      'Molosso italiano imponente e equilibrado. Excelente guardião da família com socialização e treino sérios; pede dono experiente.',
    size: 'large',
    weightMinKg: 40,
    weightMaxKg: 50,
    lifespanMinYrs: 9,
    lifespanMaxYrs: 12,
    coatLength: 'short',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 75,
    trainability: 4,
    barkLevel: 'medium',
    groomingLevel: 1,
    goodWithKids: 4,
    goodWithDogs: 2,
    goodWithStrangers: 2,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 2,
    coldTolerance: 3,
    heatTolerance: 3,
  },
  {
    nameSlug: 'cao-boieiro-australiano',
    namePt: 'Cão Boieiro Australiano (Australian Cattle Dog)',
    fciGroup: 'Grupo 1 — Cães de pastor',
    origin: 'Austrália',
    summaryPt:
      'Pastor de gado robusto e hiperinteligente. Energia inesgotável e instinto de trabalho — perfeito para desporto canino e quintas activas.',
    size: 'medium',
    weightMinKg: 15,
    weightMaxKg: 22,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 16,
    coatLength: 'short',
    shedding: 4,
    hypoallergenic: false,
    energyLevel: 5,
    exerciseDailyMin: 120,
    trainability: 5,
    barkLevel: 'medium',
    groomingLevel: 2,
    goodWithKids: 3,
    goodWithDogs: 3,
    goodWithStrangers: 2,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 1,
    coldTolerance: 4,
    heatTolerance: 4,
  },
  {
    nameSlug: 'cao-boieiro-de-berna',
    namePt: 'Cão Boieiro de Berna (Bernese Mountain Dog)',
    fciGroup: 'Grupo 2 — Pinscher e Schnauzer / Molossóides',
    origin: 'Suíça',
    summaryPt:
      'Gigante tricolor, gentil e familiar. Tranquilo, paciente com crianças; resiste mal ao calor e tem expectativa de vida curta.',
    size: 'giant',
    weightMinKg: 36,
    weightMaxKg: 50,
    lifespanMinYrs: 7,
    lifespanMaxYrs: 9,
    coatLength: 'long',
    shedding: 5,
    hypoallergenic: false,
    energyLevel: 3,
    exerciseDailyMin: 60,
    trainability: 4,
    barkLevel: 'medium',
    groomingLevel: 4,
    goodWithKids: 5,
    goodWithDogs: 4,
    goodWithStrangers: 4,
    apartmentFriendly: false,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 5,
    heatTolerance: 1,
  },
  {
    nameSlug: 'cao-castro-laboreiro',
    namePt: 'Cão de Castro Laboreiro',
    fciGroup: 'Grupo 2 — Pinscher e Schnauzer / Molossóides',
    origin: 'Portugal (Minho)',
    summaryPt:
      'Antigo cão de gado da serra de Castro Laboreiro. Resistente, vigilante e desconfiado — guardião sério para meio rural.',
    size: 'large',
    weightMinKg: 25,
    weightMaxKg: 40,
    lifespanMinYrs: 11,
    lifespanMaxYrs: 13,
    coatLength: 'short',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 75,
    trainability: 3,
    barkLevel: 'high',
    groomingLevel: 2,
    goodWithKids: 4,
    goodWithDogs: 3,
    goodWithStrangers: 1,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 3,
    coldTolerance: 4,
    heatTolerance: 3,
  },
  {
    nameSlug: 'cao-da-terra-nova',
    namePt: 'Cão da Terra Nova (Newfoundland)',
    fciGroup: 'Grupo 2 — Pinscher e Schnauzer / Molossóides',
    origin: 'Canadá',
    summaryPt:
      'Gigante de coração mole. Excelente nadador (pés palmados) e salvador aquático tradicional. Calmo, paciente e familiar.',
    size: 'giant',
    weightMinKg: 50,
    weightMaxKg: 70,
    lifespanMinYrs: 8,
    lifespanMaxYrs: 10,
    coatLength: 'long',
    shedding: 5,
    hypoallergenic: false,
    energyLevel: 2,
    exerciseDailyMin: 60,
    trainability: 4,
    barkLevel: 'low',
    groomingLevel: 4,
    goodWithKids: 5,
    goodWithDogs: 4,
    goodWithStrangers: 4,
    apartmentFriendly: false,
    noviceFriendly: true,
    toleratesAlone: 3,
    coldTolerance: 5,
    heatTolerance: 1,
  },
  {
    nameSlug: 'cao-de-fila-de-sao-miguel',
    namePt: 'Cão de Fila de São Miguel',
    fciGroup: 'Grupo 2 — Pinscher e Schnauzer / Molossóides',
    origin: 'Portugal (Açores)',
    summaryPt:
      'Molosso açoreano usado para condução de gado. Robusto, corajoso e dócil com a família; reservado com estranhos.',
    size: 'large',
    weightMinKg: 25,
    weightMaxKg: 35,
    lifespanMinYrs: 10,
    lifespanMaxYrs: 13,
    coatLength: 'short',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 75,
    trainability: 3,
    barkLevel: 'medium',
    groomingLevel: 1,
    goodWithKids: 4,
    goodWithDogs: 3,
    goodWithStrangers: 2,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 3,
    coldTolerance: 3,
    heatTolerance: 4,
  },
  {
    nameSlug: 'cao-de-gado-transmontano',
    namePt: 'Cão de Gado Transmontano',
    fciGroup: 'Grupo 2 — Pinscher e Schnauzer / Molossóides',
    origin: 'Portugal (Trás-os-Montes)',
    summaryPt:
      'O maior cão de gado português. Imponente, calmo e independente; vive entre o rebanho e protege-o do lobo. Guardião puro, não pet urbano.',
    size: 'giant',
    weightMinKg: 45,
    weightMaxKg: 60,
    lifespanMinYrs: 10,
    lifespanMaxYrs: 13,
    coatLength: 'medium',
    shedding: 4,
    hypoallergenic: false,
    energyLevel: 3,
    exerciseDailyMin: 90,
    trainability: 2,
    barkLevel: 'high',
    groomingLevel: 2,
    goodWithKids: 4,
    goodWithDogs: 2,
    goodWithStrangers: 1,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 4,
    coldTolerance: 5,
    heatTolerance: 3,
  },
  {
    nameSlug: 'cao-de-montanha-dos-pirineus',
    namePt: 'Cão de Montanha dos Pirinéus (Patou)',
    fciGroup: 'Grupo 2 — Pinscher e Schnauzer / Molossóides',
    origin: 'França',
    summaryPt:
      'Grande guardião branco dos Pirinéus. Independente, vigilante e nocturno por instinto — adequado a quintas, não a apartamento.',
    size: 'giant',
    weightMinKg: 45,
    weightMaxKg: 60,
    lifespanMinYrs: 10,
    lifespanMaxYrs: 12,
    coatLength: 'long',
    shedding: 5,
    hypoallergenic: false,
    energyLevel: 2,
    exerciseDailyMin: 60,
    trainability: 2,
    barkLevel: 'high',
    groomingLevel: 4,
    goodWithKids: 4,
    goodWithDogs: 3,
    goodWithStrangers: 2,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 4,
    coldTolerance: 5,
    heatTolerance: 1,
  },
  {
    nameSlug: 'cao-do-barrocal-algarvio',
    namePt: 'Cão do Barrocal Algarvio',
    fciGroup: 'Grupo 5 — Spitz e tipo primitivo (não FCI; reconhecido pelo CPC)',
    origin: 'Portugal (Algarve)',
    summaryPt:
      'Raça portuguesa em recuperação, originária do barrocal algarvio. Cão de caça versátil, rústico e equilibrado.',
    size: 'medium',
    weightMinKg: 16,
    weightMaxKg: 24,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 14,
    coatLength: 'short',
    shedding: 2,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 75,
    trainability: 3,
    barkLevel: 'medium',
    groomingLevel: 1,
    goodWithKids: 4,
    goodWithDogs: 3,
    goodWithStrangers: 3,
    apartmentFriendly: false,
    noviceFriendly: true,
    toleratesAlone: 3,
    coldTolerance: 3,
    heatTolerance: 5,
  },
  {
    nameSlug: 'cao-lobo-checoslovaco',
    namePt: 'Cão Lobo Checoslovaco',
    fciGroup: 'Grupo 1 — Cães de pastor',
    origin: 'Checoslováquia',
    summaryPt:
      'Cruzamento experimental entre Pastor Alemão e lobo dos Cárpatos. Atlético, independente e vocal (uiva). Pede tutor experiente em comportamento canino.',
    size: 'large',
    weightMinKg: 20,
    weightMaxKg: 35,
    lifespanMinYrs: 13,
    lifespanMaxYrs: 16,
    coatLength: 'medium',
    shedding: 4,
    hypoallergenic: false,
    energyLevel: 5,
    exerciseDailyMin: 120,
    trainability: 3,
    barkLevel: 'low',
    groomingLevel: 2,
    goodWithKids: 3,
    goodWithDogs: 3,
    goodWithStrangers: 1,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 2,
    coldTolerance: 5,
    heatTolerance: 2,
  },
  {
    nameSlug: 'cao-pastor-belga',
    namePt: 'Cão de Pastor Belga (Malinois / Tervuren / Groenendael / Laekenois)',
    fciGroup: 'Grupo 1 — Cães de pastor',
    origin: 'Bélgica',
    summaryPt:
      'Pastor de eleição em forças policiais e militares (variante Malinois). Hiperinteligente, dedicado e exigente — pede trabalho diário sério.',
    size: 'large',
    weightMinKg: 20,
    weightMaxKg: 30,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 14,
    coatLength: 'medium',
    shedding: 4,
    hypoallergenic: false,
    energyLevel: 5,
    exerciseDailyMin: 120,
    trainability: 5,
    barkLevel: 'medium',
    groomingLevel: 2,
    goodWithKids: 4,
    goodWithDogs: 3,
    goodWithStrangers: 2,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 1,
    coldTolerance: 4,
    heatTolerance: 3,
  },
  {
    nameSlug: 'cao-pastor-branco-suico',
    namePt: 'Cão de Pastor Branco Suíço',
    fciGroup: 'Grupo 1 — Cães de pastor',
    origin: 'Suíça',
    summaryPt:
      'Variante branca do Pastor Alemão, reconhecida como raça independente. Equilibrado, sociável e mais sensível — bom cão de família activa.',
    size: 'large',
    weightMinKg: 25,
    weightMaxKg: 40,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 14,
    coatLength: 'medium',
    shedding: 4,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 90,
    trainability: 5,
    barkLevel: 'medium',
    groomingLevel: 3,
    goodWithKids: 5,
    goodWithDogs: 4,
    goodWithStrangers: 3,
    apartmentFriendly: false,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 4,
    heatTolerance: 3,
  },
  {
    nameSlug: 'cao-pastor-caucaso',
    namePt: 'Cão de Pastor do Cáucaso (Ovcharka)',
    fciGroup: 'Grupo 2 — Pinscher e Schnauzer / Molossóides',
    origin: 'Rússia / Cáucaso',
    summaryPt:
      'Guardião de rebanhos de gigantesco porte e enorme valor protector. Independente, territorial e desconfiado — só para tutores muito experientes.',
    size: 'giant',
    weightMinKg: 45,
    weightMaxKg: 80,
    lifespanMinYrs: 10,
    lifespanMaxYrs: 12,
    coatLength: 'long',
    shedding: 5,
    hypoallergenic: false,
    energyLevel: 2,
    exerciseDailyMin: 60,
    trainability: 2,
    barkLevel: 'high',
    groomingLevel: 4,
    goodWithKids: 3,
    goodWithDogs: 1,
    goodWithStrangers: 1,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 4,
    coldTolerance: 5,
    heatTolerance: 1,
  },
  {
    nameSlug: 'cao-pastor-holandes',
    namePt: 'Cão de Pastor Holandês (Hollandse Herder)',
    fciGroup: 'Grupo 1 — Cães de pastor',
    origin: 'Países Baixos',
    summaryPt:
      'Pastor versátil semelhante ao Belga; pelagem tigrada característica. Inteligente, leal e atlético — usado em desporto canino e protecção.',
    size: 'large',
    weightMinKg: 23,
    weightMaxKg: 32,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 15,
    coatLength: 'short',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 5,
    exerciseDailyMin: 120,
    trainability: 5,
    barkLevel: 'medium',
    groomingLevel: 2,
    goodWithKids: 4,
    goodWithDogs: 3,
    goodWithStrangers: 2,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 2,
    coldTolerance: 4,
    heatTolerance: 3,
  },
  {
    nameSlug: 'cao-pastor-kangal',
    namePt: 'Cão de Pastor Kangal (Anatolian)',
    fciGroup: 'Grupo 2 — Pinscher e Schnauzer / Molossóides',
    origin: 'Turquia',
    summaryPt:
      'Guardião milenar dos rebanhos da Anatólia. Imponente, equilibrado e com mordedura das mais potentes do mundo canino. Não é cão de cidade.',
    size: 'giant',
    weightMinKg: 41,
    weightMaxKg: 65,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 15,
    coatLength: 'short',
    shedding: 4,
    hypoallergenic: false,
    energyLevel: 3,
    exerciseDailyMin: 75,
    trainability: 3,
    barkLevel: 'medium',
    groomingLevel: 2,
    goodWithKids: 4,
    goodWithDogs: 2,
    goodWithStrangers: 1,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 4,
    coldTolerance: 4,
    heatTolerance: 4,
  },
  {
    nameSlug: 'cao-serra-de-aires',
    namePt: 'Cão da Serra de Aires',
    fciGroup: 'Grupo 1 — Cães de pastor',
    origin: 'Portugal (Alentejo)',
    summaryPt:
      'Pastor alentejano de pelagem comprida e olhar travesso. "Cão-macaco" pela esperteza; activo, leal e excelente para famílias com espaço.',
    size: 'medium',
    weightMinKg: 17,
    weightMaxKg: 27,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 14,
    coatLength: 'long',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 75,
    trainability: 4,
    barkLevel: 'medium',
    groomingLevel: 4,
    goodWithKids: 5,
    goodWithDogs: 4,
    goodWithStrangers: 3,
    apartmentFriendly: false,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 3,
    heatTolerance: 4,
  },
  {
    nameSlug: 'cao-sem-pelo-mexico',
    namePt: 'Cão Sem Pêlo do México (Xoloitzcuintle)',
    fciGroup: 'Grupo 5 — Spitz e tipo primitivo',
    origin: 'México',
    summaryPt:
      'Raça pré-colombiana de pele nua. Calmo, atento e leal; pele exige protecção solar. Variantes em três tamanhos.',
    size: 'medium',
    weightMinKg: 9,
    weightMaxKg: 25,
    lifespanMinYrs: 13,
    lifespanMaxYrs: 18,
    coatLength: 'short',
    shedding: 1,
    hypoallergenic: true,
    energyLevel: 3,
    exerciseDailyMin: 45,
    trainability: 4,
    barkLevel: 'medium',
    groomingLevel: 2,
    goodWithKids: 4,
    goodWithDogs: 3,
    goodWithStrangers: 2,
    apartmentFriendly: true,
    noviceFriendly: false,
    toleratesAlone: 2,
    coldTolerance: 1,
    heatTolerance: 5,
  },
  {
    nameSlug: 'chinese-crested-dog',
    namePt: 'Cão de Crista Chinês (Chinese Crested)',
    fciGroup: 'Grupo 9 — Companhia',
    origin: 'China',
    summaryPt:
      'Pequeno cão sem pêlo (variante hairless) ou peludo (powder puff). Carinhoso, ligado à família e adequado a apartamento. Pele pede cuidados.',
    size: 'small',
    weightMinKg: 4,
    weightMaxKg: 6,
    lifespanMinYrs: 13,
    lifespanMaxYrs: 18,
    coatLength: 'short',
    shedding: 1,
    hypoallergenic: true,
    energyLevel: 3,
    exerciseDailyMin: 30,
    trainability: 3,
    barkLevel: 'medium',
    groomingLevel: 3,
    goodWithKids: 4,
    goodWithDogs: 3,
    goodWithStrangers: 3,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 1,
    heatTolerance: 4,
  },
  {
    nameSlug: 'chow-chow',
    namePt: 'Chow Chow',
    fciGroup: 'Grupo 5 — Spitz e tipo primitivo',
    origin: 'China',
    summaryPt:
      'Cão-leão de língua azul, pelagem leonina e ar digno. Reservado, independente e leal a uma só pessoa; pouco tolerante a estranhos.',
    size: 'medium',
    weightMinKg: 20,
    weightMaxKg: 32,
    lifespanMinYrs: 9,
    lifespanMaxYrs: 12,
    coatLength: 'long',
    shedding: 5,
    hypoallergenic: false,
    energyLevel: 2,
    exerciseDailyMin: 45,
    trainability: 2,
    barkLevel: 'low',
    groomingLevel: 5,
    goodWithKids: 3,
    goodWithDogs: 2,
    goodWithStrangers: 2,
    apartmentFriendly: true,
    noviceFriendly: false,
    toleratesAlone: 4,
    coldTolerance: 5,
    heatTolerance: 1,
  },
  {
    nameSlug: 'cocker-spaniel-americano',
    namePt: 'Cocker Spaniel Americano',
    fciGroup: 'Grupo 8 — Cães de água / patas',
    origin: 'EUA',
    summaryPt:
      'Variante americana do Cocker, mais pequena e com pelagem mais profusa. Doce, brincalhão e vocal — companheiro afável de família.',
    size: 'small',
    weightMinKg: 11,
    weightMaxKg: 14,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 15,
    coatLength: 'long',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 3,
    exerciseDailyMin: 60,
    trainability: 4,
    barkLevel: 'medium',
    groomingLevel: 5,
    goodWithKids: 5,
    goodWithDogs: 4,
    goodWithStrangers: 4,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 3,
    heatTolerance: 3,
  },
  {
    nameSlug: 'collie-pelo-comprido',
    namePt: 'Collie de Pêlo Comprido (Rough Collie)',
    fciGroup: 'Grupo 1 — Cães de pastor',
    origin: 'Escócia',
    summaryPt:
      'O cão de "Lassie". Elegante, gentil e dedicado à família; excelente com crianças. Pelagem longa pede escovagem regular.',
    size: 'large',
    weightMinKg: 23,
    weightMaxKg: 34,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 14,
    coatLength: 'long',
    shedding: 5,
    hypoallergenic: false,
    energyLevel: 3,
    exerciseDailyMin: 60,
    trainability: 5,
    barkLevel: 'medium',
    groomingLevel: 4,
    goodWithKids: 5,
    goodWithDogs: 4,
    goodWithStrangers: 4,
    apartmentFriendly: false,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 5,
    heatTolerance: 2,
  },
  {
    nameSlug: 'dogue-alemao',
    namePt: 'Dogue Alemão (Great Dane)',
    fciGroup: 'Grupo 2 — Pinscher e Schnauzer / Molossóides',
    origin: 'Alemanha',
    summaryPt:
      '"Apolo dos cães" — um dos maiores cães do mundo. Gentil gigante, elegante e familiar; vida curta é a maior nota negativa.',
    size: 'giant',
    weightMinKg: 45,
    weightMaxKg: 90,
    lifespanMinYrs: 7,
    lifespanMaxYrs: 10,
    coatLength: 'short',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 3,
    exerciseDailyMin: 60,
    trainability: 3,
    barkLevel: 'low',
    groomingLevel: 1,
    goodWithKids: 4,
    goodWithDogs: 3,
    goodWithStrangers: 4,
    apartmentFriendly: false,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 2,
    heatTolerance: 3,
  },
  {
    nameSlug: 'dogue-argentino',
    namePt: 'Dogue Argentino',
    fciGroup: 'Grupo 2 — Pinscher e Schnauzer / Molossóides',
    origin: 'Argentina',
    summaryPt:
      'Molosso branco desenvolvido para caça de javali. Atlético, corajoso e familiar; pede dono firme, espaço e socialização cuidada.',
    size: 'large',
    weightMinKg: 35,
    weightMaxKg: 50,
    lifespanMinYrs: 10,
    lifespanMaxYrs: 12,
    coatLength: 'short',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 90,
    trainability: 4,
    barkLevel: 'medium',
    groomingLevel: 1,
    goodWithKids: 4,
    goodWithDogs: 2,
    goodWithStrangers: 2,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 2,
    coldTolerance: 2,
    heatTolerance: 4,
  },
  {
    nameSlug: 'dogue-bordeus',
    namePt: 'Dogue de Bordéus',
    fciGroup: 'Grupo 2 — Pinscher e Schnauzer / Molossóides',
    origin: 'França',
    summaryPt:
      'Molosso francês de cabeça enorme e expressão preocupada. Calmo, devoto e familiar; ronco e babar são parte do pacote.',
    size: 'giant',
    weightMinKg: 45,
    weightMaxKg: 65,
    lifespanMinYrs: 5,
    lifespanMaxYrs: 8,
    coatLength: 'short',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 2,
    exerciseDailyMin: 45,
    trainability: 3,
    barkLevel: 'low',
    groomingLevel: 1,
    goodWithKids: 4,
    goodWithDogs: 2,
    goodWithStrangers: 3,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 3,
    coldTolerance: 2,
    heatTolerance: 1,
  },
  {
    nameSlug: 'dogue-tibete',
    namePt: 'Dogue do Tibete (Tibetan Mastiff)',
    fciGroup: 'Grupo 2 — Pinscher e Schnauzer / Molossóides',
    origin: 'Tibete',
    summaryPt:
      'Antigo guardião dos mosteiros himalaicos. Imponente, independente e nocturno por instinto. Não recomendado para principiantes ou apartamento.',
    size: 'giant',
    weightMinKg: 45,
    weightMaxKg: 75,
    lifespanMinYrs: 10,
    lifespanMaxYrs: 14,
    coatLength: 'long',
    shedding: 4,
    hypoallergenic: false,
    energyLevel: 2,
    exerciseDailyMin: 60,
    trainability: 2,
    barkLevel: 'high',
    groomingLevel: 4,
    goodWithKids: 3,
    goodWithDogs: 2,
    goodWithStrangers: 1,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 4,
    coldTolerance: 5,
    heatTolerance: 1,
  },
  {
    nameSlug: 'english-springer-spaniel',
    namePt: 'English Springer Spaniel',
    fciGroup: 'Grupo 8 — Cães de água / patas',
    origin: 'Inglaterra',
    summaryPt:
      'Spaniel de caça versátil e enérgico. Sociável, treinável e excelente companheiro de família activa; pelagem ondulada de manutenção média.',
    size: 'medium',
    weightMinKg: 18,
    weightMaxKg: 25,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 14,
    coatLength: 'medium',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 5,
    exerciseDailyMin: 90,
    trainability: 5,
    barkLevel: 'medium',
    groomingLevel: 3,
    goodWithKids: 5,
    goodWithDogs: 4,
    goodWithStrangers: 4,
    apartmentFriendly: false,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 4,
    heatTolerance: 3,
  },
  {
    nameSlug: 'epagneul-bretao',
    namePt: 'Epagneul Bretão (Brittany)',
    fciGroup: 'Grupo 7 — Cães de parar',
    origin: 'França',
    summaryPt:
      'Cão de caça compacto e versátil — o mais pequeno dos pointers. Inteligente, dócil e bom para famílias activas com espaço.',
    size: 'medium',
    weightMinKg: 14,
    weightMaxKg: 18,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 14,
    coatLength: 'medium',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 5,
    exerciseDailyMin: 90,
    trainability: 4,
    barkLevel: 'medium',
    groomingLevel: 2,
    goodWithKids: 5,
    goodWithDogs: 4,
    goodWithStrangers: 4,
    apartmentFriendly: false,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 4,
    heatTolerance: 3,
  },
  {
    nameSlug: 'fox-terrier-pelo-liso',
    namePt: 'Fox Terrier de Pêlo Liso',
    fciGroup: 'Grupo 3 — Terriers',
    origin: 'Inglaterra',
    summaryPt:
      'Terrier clássico, vivo e teimoso. Coragem desproporcional ao tamanho; pede tutor com sentido de humor e mão firme.',
    size: 'small',
    weightMinKg: 6.5,
    weightMaxKg: 8,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 15,
    coatLength: 'short',
    shedding: 2,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 60,
    trainability: 3,
    barkLevel: 'high',
    groomingLevel: 2,
    goodWithKids: 4,
    goodWithDogs: 3,
    goodWithStrangers: 3,
    apartmentFriendly: true,
    noviceFriendly: false,
    toleratesAlone: 2,
    coldTolerance: 3,
    heatTolerance: 3,
  },
  {
    nameSlug: 'galgo-italiano',
    namePt: 'Galgo Italiano (Galguinho)',
    fciGroup: 'Grupo 10 — Lebreiros',
    origin: 'Itália',
    summaryPt:
      'Lebreiro miniatura, elegante e frágil. Velocíssimo apesar do tamanho; carinhoso, sensível e ideal para apartamento sossegado.',
    size: 'small',
    weightMinKg: 3.5,
    weightMaxKg: 5,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 15,
    coatLength: 'short',
    shedding: 1,
    hypoallergenic: false,
    energyLevel: 3,
    exerciseDailyMin: 45,
    trainability: 3,
    barkLevel: 'low',
    groomingLevel: 1,
    goodWithKids: 3,
    goodWithDogs: 4,
    goodWithStrangers: 3,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 1,
    heatTolerance: 4,
  },
  {
    nameSlug: 'greyhound',
    namePt: 'Galgo Inglês (Greyhound)',
    fciGroup: 'Grupo 10 — Lebreiros',
    origin: 'Inglaterra',
    summaryPt:
      'O cão mais rápido do mundo. Surpreendentemente calmo em casa — "atleta de sofá" que adora dormir. Pede passeios à trela.',
    size: 'large',
    weightMinKg: 25,
    weightMaxKg: 40,
    lifespanMinYrs: 10,
    lifespanMaxYrs: 13,
    coatLength: 'short',
    shedding: 2,
    hypoallergenic: false,
    energyLevel: 3,
    exerciseDailyMin: 45,
    trainability: 3,
    barkLevel: 'low',
    groomingLevel: 1,
    goodWithKids: 4,
    goodWithDogs: 3,
    goodWithStrangers: 3,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 3,
    coldTolerance: 1,
    heatTolerance: 3,
  },
  {
    nameSlug: 'mastim-ingles',
    namePt: 'Mastim Inglês',
    fciGroup: 'Grupo 2 — Pinscher e Schnauzer / Molossóides',
    origin: 'Inglaterra',
    summaryPt:
      'Um dos cães mais pesados do mundo. Calmo, dócil e familiar; presença imponente é dissuasor natural. Vida curta.',
    size: 'giant',
    weightMinKg: 70,
    weightMaxKg: 100,
    lifespanMinYrs: 6,
    lifespanMaxYrs: 10,
    coatLength: 'short',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 2,
    exerciseDailyMin: 45,
    trainability: 3,
    barkLevel: 'low',
    groomingLevel: 1,
    goodWithKids: 5,
    goodWithDogs: 3,
    goodWithStrangers: 3,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 3,
    coldTolerance: 2,
    heatTolerance: 2,
  },
  {
    nameSlug: 'miniature-american-shepherd',
    namePt: 'Miniature American Shepherd',
    fciGroup: 'Grupo 1 — Cães de pastor',
    origin: 'EUA',
    summaryPt:
      'Versão compacta do Pastor Australiano (não confundir com Aussie). Vivo, treinável e enérgico — excelente para desporto canino.',
    size: 'small',
    weightMinKg: 9,
    weightMaxKg: 18,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 13,
    coatLength: 'medium',
    shedding: 4,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 75,
    trainability: 5,
    barkLevel: 'medium',
    groomingLevel: 3,
    goodWithKids: 5,
    goodWithDogs: 4,
    goodWithStrangers: 4,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 4,
    heatTolerance: 3,
  },
  {
    nameSlug: 'nova-scotia-duck-tolling-retriever',
    namePt: 'Nova Scotia Duck Tolling Retriever (Toller)',
    fciGroup: 'Grupo 8 — Cães de água / patas',
    origin: 'Canadá',
    summaryPt:
      'O mais pequeno dos retrievers. Inteligente, brincalhão e enérgico; especialidade canadiana é "tolar" — atrair patos com brincadeiras na margem.',
    size: 'medium',
    weightMinKg: 17,
    weightMaxKg: 23,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 14,
    coatLength: 'medium',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 5,
    exerciseDailyMin: 90,
    trainability: 5,
    barkLevel: 'medium',
    groomingLevel: 3,
    goodWithKids: 5,
    goodWithDogs: 4,
    goodWithStrangers: 4,
    apartmentFriendly: false,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 4,
    heatTolerance: 3,
  },
  {
    nameSlug: 'pequines',
    namePt: 'Pequinês',
    fciGroup: 'Grupo 9 — Companhia',
    origin: 'China',
    summaryPt:
      'Antigo cão imperial chinês. Pequeno, leonino e digno — independente como um gato. Pelagem longa exige cuidados.',
    size: 'small',
    weightMinKg: 3,
    weightMaxKg: 6,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 15,
    coatLength: 'long',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 2,
    exerciseDailyMin: 30,
    trainability: 2,
    barkLevel: 'medium',
    groomingLevel: 5,
    goodWithKids: 3,
    goodWithDogs: 3,
    goodWithStrangers: 3,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 3,
    coldTolerance: 3,
    heatTolerance: 1,
  },
  {
    nameSlug: 'perdigueiro-portugues',
    namePt: 'Perdigueiro Português',
    fciGroup: 'Grupo 7 — Cães de parar',
    origin: 'Portugal',
    summaryPt:
      'Cão de parar nacional de origem ibérica. Equilibrado, dócil e excelente caçador de perdiz; também óptimo cão de família activa.',
    size: 'medium',
    weightMinKg: 16,
    weightMaxKg: 27,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 14,
    coatLength: 'short',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 90,
    trainability: 4,
    barkLevel: 'medium',
    groomingLevel: 1,
    goodWithKids: 5,
    goodWithDogs: 4,
    goodWithStrangers: 4,
    apartmentFriendly: false,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 3,
    heatTolerance: 4,
  },
  {
    nameSlug: 'pointer-ingles',
    namePt: 'Pointer (Inglês)',
    fciGroup: 'Grupo 7 — Cães de parar',
    origin: 'Inglaterra',
    summaryPt:
      'Cão de parar puro, atlético e elegante. Pose escultural quando localiza caça; precisa de muito exercício e estímulo mental.',
    size: 'large',
    weightMinKg: 20,
    weightMaxKg: 34,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 14,
    coatLength: 'short',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 5,
    exerciseDailyMin: 120,
    trainability: 4,
    barkLevel: 'low',
    groomingLevel: 1,
    goodWithKids: 4,
    goodWithDogs: 4,
    goodWithStrangers: 4,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 1,
    coldTolerance: 2,
    heatTolerance: 4,
  },
  {
    nameSlug: 'presa-canario',
    namePt: 'Presa Canário (Dogo Canario)',
    fciGroup: 'Grupo 2 — Pinscher e Schnauzer / Molossóides',
    origin: 'Espanha (Canárias)',
    summaryPt:
      'Molosso canário potente e territorial. Equilibrado em casa, intimidante com estranhos. Tutor experiente, socialização precoce e treino consistente são essenciais.',
    size: 'large',
    weightMinKg: 40,
    weightMaxKg: 65,
    lifespanMinYrs: 9,
    lifespanMaxYrs: 11,
    coatLength: 'short',
    shedding: 2,
    hypoallergenic: false,
    energyLevel: 3,
    exerciseDailyMin: 60,
    trainability: 4,
    barkLevel: 'medium',
    groomingLevel: 1,
    goodWithKids: 4,
    goodWithDogs: 2,
    goodWithStrangers: 2,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 3,
    coldTolerance: 3,
    heatTolerance: 4,
  },
  {
    nameSlug: 'ratonero-bodeguero-andaluz',
    namePt: 'Ratonero-Bodeguero Andaluz',
    fciGroup: 'Grupo 3 — Terriers (não FCI; reconhecido por RFEC)',
    origin: 'Espanha (Andaluzia)',
    summaryPt:
      'Pequeno terrier andaluz das adegas, especialista no controlo de ratos. Ágil, atento e companheiro fiel.',
    size: 'small',
    weightMinKg: 6,
    weightMaxKg: 9,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 15,
    coatLength: 'short',
    shedding: 2,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 60,
    trainability: 3,
    barkLevel: 'medium',
    groomingLevel: 1,
    goodWithKids: 4,
    goodWithDogs: 3,
    goodWithStrangers: 3,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 3,
    heatTolerance: 4,
  },
  {
    nameSlug: 'rhodesian-ridgeback',
    namePt: 'Rhodesian Ridgeback (Leão da Rodésia)',
    fciGroup: 'Grupo 6 — Cães de corrida e farejadores',
    origin: 'África do Sul / Zimbabué',
    summaryPt:
      'Crista de pêlo invertida ao longo da espinha. Caçador de leões na origem; calmo e leal em casa, atlético e determinado.',
    size: 'large',
    weightMinKg: 30,
    weightMaxKg: 40,
    lifespanMinYrs: 10,
    lifespanMaxYrs: 12,
    coatLength: 'short',
    shedding: 2,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 75,
    trainability: 3,
    barkLevel: 'low',
    groomingLevel: 1,
    goodWithKids: 4,
    goodWithDogs: 3,
    goodWithStrangers: 2,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 3,
    coldTolerance: 2,
    heatTolerance: 5,
  },
  {
    nameSlug: 'sabujo-bavaro',
    namePt: 'Sabujo Bávaro de Montanha (Bayrischer Gebirgsschweisshund)',
    fciGroup: 'Grupo 6 — Cães de corrida e farejadores',
    origin: 'Alemanha',
    summaryPt:
      'Especialista em rastreio de caça ferida em terreno montanhoso. Calmo, equilibrado e apegado ao tutor; pouco conhecido fora do meio venatório.',
    size: 'medium',
    weightMinKg: 17,
    weightMaxKg: 30,
    lifespanMinYrs: 10,
    lifespanMaxYrs: 14,
    coatLength: 'short',
    shedding: 2,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 90,
    trainability: 4,
    barkLevel: 'medium',
    groomingLevel: 1,
    goodWithKids: 4,
    goodWithDogs: 3,
    goodWithStrangers: 3,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 2,
    coldTolerance: 4,
    heatTolerance: 3,
  },
  {
    nameSlug: 'schipperke',
    namePt: 'Schipperke',
    fciGroup: 'Grupo 1 — Cães de pastor',
    origin: 'Bélgica',
    summaryPt:
      'Pequeno cão preto de aparência de mini-spitz. Vivo, alerta e excelente cão de alarme; tradicionalmente cão dos barcaços flamengos.',
    size: 'small',
    weightMinKg: 3,
    weightMaxKg: 9,
    lifespanMinYrs: 13,
    lifespanMaxYrs: 16,
    coatLength: 'medium',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 60,
    trainability: 4,
    barkLevel: 'high',
    groomingLevel: 2,
    goodWithKids: 4,
    goodWithDogs: 3,
    goodWithStrangers: 2,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 3,
    coldTolerance: 4,
    heatTolerance: 3,
  },
  {
    nameSlug: 'schnauzer-gigante',
    namePt: 'Schnauzer Gigante',
    fciGroup: 'Grupo 2 — Pinscher e Schnauzer / Molossóides',
    origin: 'Alemanha',
    summaryPt:
      'A versão maior da família Schnauzer. Imponente, trabalhador e leal; usado em forças militares. Pelagem dura pede stripping regular.',
    size: 'large',
    weightMinKg: 32,
    weightMaxKg: 48,
    lifespanMinYrs: 10,
    lifespanMaxYrs: 12,
    coatLength: 'medium',
    shedding: 1,
    hypoallergenic: true,
    energyLevel: 4,
    exerciseDailyMin: 90,
    trainability: 5,
    barkLevel: 'medium',
    groomingLevel: 4,
    goodWithKids: 4,
    goodWithDogs: 3,
    goodWithStrangers: 2,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 2,
    coldTolerance: 4,
    heatTolerance: 3,
  },
  {
    nameSlug: 'schnauzer-medio',
    namePt: 'Schnauzer Médio (Standard)',
    fciGroup: 'Grupo 2 — Pinscher e Schnauzer / Molossóides',
    origin: 'Alemanha',
    summaryPt:
      'O original da linha Schnauzer. Versátil, alerta e treinável; bom cão de família e guarda equilibrado.',
    size: 'medium',
    weightMinKg: 14,
    weightMaxKg: 20,
    lifespanMinYrs: 13,
    lifespanMaxYrs: 16,
    coatLength: 'medium',
    shedding: 1,
    hypoallergenic: true,
    energyLevel: 4,
    exerciseDailyMin: 60,
    trainability: 5,
    barkLevel: 'medium',
    groomingLevel: 4,
    goodWithKids: 4,
    goodWithDogs: 3,
    goodWithStrangers: 3,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 4,
    heatTolerance: 3,
  },
  {
    nameSlug: 'setter-ingles',
    namePt: 'Setter Inglês',
    fciGroup: 'Grupo 7 — Cães de parar',
    origin: 'Inglaterra',
    summaryPt:
      'Cão de parar elegantíssimo, com pelagem mosqueada (belton). Doce, sociável e de grande resistência; pede família activa.',
    size: 'large',
    weightMinKg: 20,
    weightMaxKg: 36,
    lifespanMinYrs: 11,
    lifespanMaxYrs: 13,
    coatLength: 'long',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 5,
    exerciseDailyMin: 120,
    trainability: 4,
    barkLevel: 'medium',
    groomingLevel: 4,
    goodWithKids: 5,
    goodWithDogs: 4,
    goodWithStrangers: 4,
    apartmentFriendly: false,
    noviceFriendly: true,
    toleratesAlone: 1,
    coldTolerance: 4,
    heatTolerance: 3,
  },
  {
    nameSlug: 'setter-irlandes-vermelho',
    namePt: 'Setter Irlandês Vermelho',
    fciGroup: 'Grupo 7 — Cães de parar',
    origin: 'Irlanda',
    summaryPt:
      'Pelagem acaju brilhante e energia exuberante. Brincalhão, afectuoso e amante de famílias activas; matura tarde — eterno cachorro.',
    size: 'large',
    weightMinKg: 24,
    weightMaxKg: 32,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 15,
    coatLength: 'long',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 5,
    exerciseDailyMin: 120,
    trainability: 4,
    barkLevel: 'medium',
    groomingLevel: 4,
    goodWithKids: 5,
    goodWithDogs: 4,
    goodWithStrangers: 4,
    apartmentFriendly: false,
    noviceFriendly: true,
    toleratesAlone: 1,
    coldTolerance: 4,
    heatTolerance: 3,
  },
  {
    nameSlug: 'vizsla',
    namePt: 'Vizsla (Braco Húngaro de Pêlo Curto)',
    fciGroup: 'Grupo 7 — Cães de parar',
    origin: 'Hungria',
    summaryPt:
      'Cão de caça versátil, dourado e elegante. Apelidado "velcro dog" — extremamente apegado ao tutor. Energia abundante, sensibilidade marcada.',
    size: 'medium',
    weightMinKg: 20,
    weightMaxKg: 30,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 14,
    coatLength: 'short',
    shedding: 2,
    hypoallergenic: false,
    energyLevel: 5,
    exerciseDailyMin: 90,
    trainability: 5,
    barkLevel: 'medium',
    groomingLevel: 1,
    goodWithKids: 5,
    goodWithDogs: 4,
    goodWithStrangers: 4,
    apartmentFriendly: false,
    noviceFriendly: true,
    toleratesAlone: 1,
    coldTolerance: 2,
    heatTolerance: 4,
  },
  {
    nameSlug: 'welsh-corgi-cardigan',
    namePt: 'Welsh Corgi Cardigan',
    fciGroup: 'Grupo 1 — Cães de pastor',
    origin: 'País de Gales',
    summaryPt:
      'Variante de cauda longa do Corgi. Pastor de gado de pernas curtas; afectuoso, vigilante e com personalidade marcante.',
    size: 'small',
    weightMinKg: 11,
    weightMaxKg: 17,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 15,
    coatLength: 'medium',
    shedding: 4,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 60,
    trainability: 4,
    barkLevel: 'high',
    groomingLevel: 3,
    goodWithKids: 4,
    goodWithDogs: 3,
    goodWithStrangers: 3,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 3,
    coldTolerance: 4,
    heatTolerance: 3,
  },
  {
    nameSlug: 'welsh-corgi-pembroke',
    namePt: 'Welsh Corgi Pembroke',
    fciGroup: 'Grupo 1 — Cães de pastor',
    origin: 'País de Gales',
    summaryPt:
      'O Corgi da rainha. Pequeno pastor de gado, esperto e vivo; sem cauda, com expressão sorridente e personalidade enorme.',
    size: 'small',
    weightMinKg: 10,
    weightMaxKg: 14,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 15,
    coatLength: 'medium',
    shedding: 4,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 60,
    trainability: 5,
    barkLevel: 'high',
    groomingLevel: 3,
    goodWithKids: 5,
    goodWithDogs: 3,
    goodWithStrangers: 3,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 3,
    coldTolerance: 4,
    heatTolerance: 3,
  },
  {
    nameSlug: 'west-highland-white-terrier',
    namePt: 'West Highland White Terrier (Westie)',
    fciGroup: 'Grupo 3 — Terriers',
    origin: 'Escócia',
    summaryPt:
      'Pequeno terrier branco escocês. Vivo, alerta e independente; adora a família mas mantém o espírito caçador de um terrier.',
    size: 'small',
    weightMinKg: 7,
    weightMaxKg: 10,
    lifespanMinYrs: 13,
    lifespanMaxYrs: 15,
    coatLength: 'medium',
    shedding: 2,
    hypoallergenic: true,
    energyLevel: 3,
    exerciseDailyMin: 45,
    trainability: 3,
    barkLevel: 'high',
    groomingLevel: 4,
    goodWithKids: 4,
    goodWithDogs: 3,
    goodWithStrangers: 3,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 3,
    coldTolerance: 4,
    heatTolerance: 3,
  },
  {
    nameSlug: 'whippet',
    namePt: 'Whippet',
    fciGroup: 'Grupo 10 — Lebreiros',
    origin: 'Inglaterra',
    summaryPt:
      'Lebreiro de tamanho médio, rápido e silencioso. Calmo em casa, explosivo no campo; companheiro carinhoso, ideal para apartamento sossegado.',
    size: 'medium',
    weightMinKg: 9,
    weightMaxKg: 19,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 15,
    coatLength: 'short',
    shedding: 2,
    hypoallergenic: false,
    energyLevel: 3,
    exerciseDailyMin: 45,
    trainability: 3,
    barkLevel: 'low',
    groomingLevel: 1,
    goodWithKids: 5,
    goodWithDogs: 4,
    goodWithStrangers: 3,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 3,
    coldTolerance: 1,
    heatTolerance: 4,
  },
]

// ─── Imagens das raças ──────────────────────────────────────────────
//
// URLs estáveis do CDN do projecto Dog CEO (https://dog.ceo/dog-api/),
// público e gratuito. Foram fixadas (não geradas em runtime) para o
// resultado ser determinístico e o seed idempotente.
//
// As 4 raças autóctones portuguesas (Estrela, Cão de Água, Podengo,
// Rafeiro) não estão cobertas pelo Dog CEO. Ficam com `null` e o
// frontend mostra um placeholder. A adicionar manualmente quando
// tivermos imagens próprias com licença clara.

const BREED_IMAGES: Record<string, string | null> = {
  'akita-inu': 'https://images.dog.ceo/breeds/akita/Akita_inu_blanc.jpg',
  beagle: 'https://images.dog.ceo/breeds/beagle/n02088364_17553.jpg',
  'bichon-maltes': 'https://images.dog.ceo/breeds/maltese/n02085936_352.jpg',
  'border-collie': 'https://images.dog.ceo/breeds/collie-border/n02106166_6545.jpg',
  boxer: 'https://images.dog.ceo/breeds/boxer/n02108089_625.jpg',
  'bulldog-frances': 'https://images.dog.ceo/breeds/bulldog-french/n02108915_4214.jpg',
  'bulldog-ingles': 'https://images.dog.ceo/breeds/bulldog-english/jager-1.jpg',
  'cao-da-serra-da-estrela': null,
  'cao-de-agua-portugues': null,
  'cavalier-king-charles': 'https://images.dog.ceo/breeds/spaniel-blenheim/n02086646_2725.jpg',
  chihuahua: 'https://images.dog.ceo/breeds/chihuahua/n02085620_4919.jpg',
  'cocker-spaniel-ingles': 'https://images.dog.ceo/breeds/spaniel-cocker/n02102318_10226.jpg',
  dalmata: 'https://images.dog.ceo/breeds/dalmatian/cooper2.jpg',
  dachshund: 'https://images.dog.ceo/breeds/dachshund/dog-1018408_640.jpg',
  doberman: 'https://images.dog.ceo/breeds/doberman/n02107142_788.jpg',
  'galgo-portugues': null, // Podengo Português — sem imagem em dog.ceo
  'golden-retriever': 'https://images.dog.ceo/breeds/retriever-golden/n02099601_3666.jpg',
  'husky-siberiano': 'https://images.dog.ceo/breeds/husky/n02110185_4115.jpg',
  'jack-russell-terrier': 'https://images.dog.ceo/breeds/terrier-russell/jack-koda-2.jpg',
  'labrador-retriever': 'https://images.dog.ceo/breeds/labrador/n02099712_4403.jpg',
  'lulu-da-pomerania': 'https://images.dog.ceo/breeds/pomeranian/n02112018_6832.jpg',
  'mastim-napolitano': 'https://images.dog.ceo/breeds/mastiff-english/2.jpg',
  'pastor-alemao': 'https://images.dog.ceo/breeds/german-shepherd/n02106662_13123.jpg',
  'pastor-australiano': 'https://images.dog.ceo/breeds/australian-shepherd/pepper2.jpg',
  'pequenino-papillon': 'https://images.dog.ceo/breeds/papillon/n02086910_2380.jpg',
  'pinscher-miniatura': 'https://images.dog.ceo/breeds/pinscher-miniature/n02107312_2893.jpg',
  'poodle-medio': 'https://images.dog.ceo/breeds/poodle-medium/PXL_20210220_100624962.jpg',
  pug: 'https://images.dog.ceo/breeds/pug/n02110958_9642.jpg',
  'rafeiro-do-alentejo': null,
  rottweiler: 'https://images.dog.ceo/breeds/rottweiler/n02106550_4254.jpg',
  samoiedo: 'https://images.dog.ceo/breeds/samoyed/n02111889_6622.jpg',
  'sao-bernardo': 'https://images.dog.ceo/breeds/stbernard/n02109525_523.jpg',
  'schnauzer-miniatura': 'https://images.dog.ceo/breeds/schnauzer-miniature/n02097047_1545.jpg',
  'shar-pei': 'https://images.dog.ceo/breeds/sharpei/noel.jpg',
  'shiba-inu': 'https://images.dog.ceo/breeds/shiba/shiba_20.jpg',
  'shih-tzu': 'https://images.dog.ceo/breeds/shihtzu/n02086240_963.jpg',
  'staffordshire-bull-terrier':
    'https://images.dog.ceo/breeds/bullterrier-staffordshire/n02093256_5646.jpg',
  weimaraner: 'https://images.dog.ceo/breeds/weimaraner/n02092339_7224.jpg',
  'yorkshire-terrier': 'https://images.dog.ceo/breeds/terrier-yorkshire/n02094433_3881.jpg',
}

// Aplica as imagens uma única vez no carregamento do módulo.
for (const breed of BREEDS) {
  if (breed.imageUrl == null) {
    breed.imageUrl = BREED_IMAGES[breed.nameSlug] ?? null
  }
}
