// ============================================
// PataCerta — Breed catalog (editorial seed)
// ============================================
//
// Dados editoriais sobre raças caninas usados pelo simulador
// "encontrar a raça ideal". Inspirados em fontes públicas (FCI, AKC,
// Purina, Wikipedia pt) mas redigidos por nós — sem republicação literal.
//
// Escalas:
//   - Atributos numéricos 1-5 (1 = baixíssimo, 5 = altíssimo)
//   - size: "small" (< 10kg) | "medium" (10-25kg) | "large" (25-45kg) | "giant" (> 45kg)
//   - coatLength: "short" | "medium" | "long"
//   - barkLevel: "low" | "medium" | "high"
//
// Manter ordenado por nameSlug.

export interface BreedSeed {
  nameSlug: string
  namePt: string
  fciGroup: string | null
  origin: string | null
  summaryPt: string
  size: 'small' | 'medium' | 'large' | 'giant'
  weightMinKg: number
  weightMaxKg: number
  lifespanMinYrs: number
  lifespanMaxYrs: number
  coatLength: 'short' | 'medium' | 'long'
  shedding: number
  hypoallergenic: boolean
  energyLevel: number
  exerciseDailyMin: number
  trainability: number
  barkLevel: 'low' | 'medium' | 'high'
  groomingLevel: number
  goodWithKids: number
  goodWithDogs: number
  goodWithStrangers: number
  apartmentFriendly: boolean
  noviceFriendly: boolean
  toleratesAlone: number
  coldTolerance: number
  heatTolerance: number
  imageUrl?: string | null
}

export const BREEDS: BreedSeed[] = [
  {
    nameSlug: 'akita-inu',
    namePt: 'Akita Inu',
    fciGroup: 'Grupo 5 — Spitz e tipo primitivo',
    origin: 'Japão',
    summaryPt:
      'Cão japonês de porte grande, leal e reservado. Forte instinto de guarda e independência — pede dono experiente.',
    size: 'large',
    weightMinKg: 32,
    weightMaxKg: 45,
    lifespanMinYrs: 10,
    lifespanMaxYrs: 13,
    coatLength: 'medium',
    shedding: 5,
    hypoallergenic: false,
    energyLevel: 3,
    exerciseDailyMin: 60,
    trainability: 3,
    barkLevel: 'low',
    groomingLevel: 4,
    goodWithKids: 3,
    goodWithDogs: 2,
    goodWithStrangers: 2,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 3,
    coldTolerance: 5,
    heatTolerance: 2,
  },
  {
    nameSlug: 'beagle',
    namePt: 'Beagle',
    fciGroup: 'Grupo 6 — Cães de corrida e farejadores',
    origin: 'Inglaterra',
    summaryPt:
      'Sabujo de tamanho médio, alegre e curioso. Vocaliza bastante e segue cheiros — bom companheiro de família activa.',
    size: 'medium',
    weightMinKg: 9,
    weightMaxKg: 14,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 15,
    coatLength: 'short',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 60,
    trainability: 3,
    barkLevel: 'high',
    groomingLevel: 2,
    goodWithKids: 5,
    goodWithDogs: 5,
    goodWithStrangers: 4,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 3,
    heatTolerance: 3,
  },
  {
    nameSlug: 'bichon-maltes',
    namePt: 'Bichon Maltês',
    fciGroup: 'Grupo 9 — Cães de companhia',
    origin: 'Mediterrâneo',
    summaryPt:
      'Pequeno, branco e elegante. Pelagem longa que requer escovagem diária. Carinhoso e adapta-se bem a apartamento.',
    size: 'small',
    weightMinKg: 3,
    weightMaxKg: 4,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 15,
    coatLength: 'long',
    shedding: 1,
    hypoallergenic: true,
    energyLevel: 3,
    exerciseDailyMin: 30,
    trainability: 4,
    barkLevel: 'medium',
    groomingLevel: 5,
    goodWithKids: 3,
    goodWithDogs: 4,
    goodWithStrangers: 4,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 3,
    heatTolerance: 3,
  },
  {
    nameSlug: 'border-collie',
    namePt: 'Border Collie',
    fciGroup: 'Grupo 1 — Cães de pastor e boieiros',
    origin: 'Reino Unido',
    summaryPt:
      'Considerada a raça mais inteligente. Energia inesgotável e necessidade absoluta de trabalho mental e físico diário.',
    size: 'medium',
    weightMinKg: 14,
    weightMaxKg: 20,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 15,
    coatLength: 'medium',
    shedding: 4,
    hypoallergenic: false,
    energyLevel: 5,
    exerciseDailyMin: 120,
    trainability: 5,
    barkLevel: 'medium',
    groomingLevel: 3,
    goodWithKids: 4,
    goodWithDogs: 4,
    goodWithStrangers: 3,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 2,
    coldTolerance: 4,
    heatTolerance: 3,
  },
  {
    nameSlug: 'boxer',
    namePt: 'Boxer',
    fciGroup: 'Grupo 2 — Pinscher, Schnauzer, Molossos',
    origin: 'Alemanha',
    summaryPt:
      'Atlético e brincalhão. Excelente com crianças, protector da família. Necessita de exercício regular.',
    size: 'large',
    weightMinKg: 25,
    weightMaxKg: 32,
    lifespanMinYrs: 10,
    lifespanMaxYrs: 12,
    coatLength: 'short',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 90,
    trainability: 4,
    barkLevel: 'medium',
    groomingLevel: 1,
    goodWithKids: 5,
    goodWithDogs: 4,
    goodWithStrangers: 3,
    apartmentFriendly: false,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 2,
    heatTolerance: 2,
  },
  {
    nameSlug: 'bulldog-frances',
    namePt: 'Bulldog Francês',
    fciGroup: 'Grupo 9 — Cães de companhia',
    origin: 'França',
    summaryPt:
      'Pequeno, musculado e afectuoso. Baixa necessidade de exercício, ideal para apartamento. Sensível ao calor.',
    size: 'small',
    weightMinKg: 8,
    weightMaxKg: 14,
    lifespanMinYrs: 10,
    lifespanMaxYrs: 12,
    coatLength: 'short',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 2,
    exerciseDailyMin: 30,
    trainability: 3,
    barkLevel: 'low',
    groomingLevel: 2,
    goodWithKids: 5,
    goodWithDogs: 4,
    goodWithStrangers: 4,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 2,
    heatTolerance: 1,
  },
  {
    nameSlug: 'bulldog-ingles',
    namePt: 'Bulldog Inglês',
    fciGroup: 'Grupo 2 — Pinscher, Schnauzer, Molossos',
    origin: 'Inglaterra',
    summaryPt:
      'Calmo, afectuoso e teimoso. Não requer muito exercício mas tem custos veterinários elevados pela morfologia.',
    size: 'medium',
    weightMinKg: 18,
    weightMaxKg: 25,
    lifespanMinYrs: 8,
    lifespanMaxYrs: 10,
    coatLength: 'short',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 2,
    exerciseDailyMin: 30,
    trainability: 2,
    barkLevel: 'low',
    groomingLevel: 2,
    goodWithKids: 5,
    goodWithDogs: 3,
    goodWithStrangers: 4,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 3,
    coldTolerance: 2,
    heatTolerance: 1,
  },
  {
    nameSlug: 'cao-da-serra-da-estrela',
    namePt: 'Cão da Serra da Estrela',
    fciGroup: 'Grupo 2 — Pinscher, Schnauzer, Molossos',
    origin: 'Portugal',
    summaryPt:
      'Raça portuguesa de montanha. Grande, robusto e protector. Tradicionalmente guardador de rebanhos.',
    size: 'giant',
    weightMinKg: 30,
    weightMaxKg: 50,
    lifespanMinYrs: 10,
    lifespanMaxYrs: 12,
    coatLength: 'long',
    shedding: 4,
    hypoallergenic: false,
    energyLevel: 3,
    exerciseDailyMin: 60,
    trainability: 3,
    barkLevel: 'medium',
    groomingLevel: 3,
    goodWithKids: 4,
    goodWithDogs: 3,
    goodWithStrangers: 2,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 4,
    coldTolerance: 5,
    heatTolerance: 2,
  },
  {
    nameSlug: 'cao-de-agua-portugues',
    namePt: 'Cão de Água Português',
    fciGroup: 'Grupo 8 — Cães de cobro, levantadores e de água',
    origin: 'Portugal',
    summaryPt:
      'Raça portuguesa, pelo encaracolado e quase sem queda. Energético, inteligente e bom companheiro para famílias activas.',
    size: 'medium',
    weightMinKg: 16,
    weightMaxKg: 25,
    lifespanMinYrs: 11,
    lifespanMaxYrs: 14,
    coatLength: 'long',
    shedding: 1,
    hypoallergenic: true,
    energyLevel: 4,
    exerciseDailyMin: 90,
    trainability: 5,
    barkLevel: 'medium',
    groomingLevel: 4,
    goodWithKids: 5,
    goodWithDogs: 4,
    goodWithStrangers: 3,
    apartmentFriendly: false,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 3,
    heatTolerance: 3,
  },
  {
    nameSlug: 'cavalier-king-charles',
    namePt: 'Cavalier King Charles Spaniel',
    fciGroup: 'Grupo 9 — Cães de companhia',
    origin: 'Reino Unido',
    summaryPt:
      'Pequeno spaniel afectuoso. Excelente com crianças e idosos. Adapta-se a apartamentos.',
    size: 'small',
    weightMinKg: 5,
    weightMaxKg: 8,
    lifespanMinYrs: 9,
    lifespanMaxYrs: 14,
    coatLength: 'long',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 3,
    exerciseDailyMin: 45,
    trainability: 4,
    barkLevel: 'low',
    groomingLevel: 4,
    goodWithKids: 5,
    goodWithDogs: 5,
    goodWithStrangers: 5,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 1,
    coldTolerance: 3,
    heatTolerance: 3,
  },
  {
    nameSlug: 'chihuahua',
    namePt: 'Chihuahua',
    fciGroup: 'Grupo 9 — Cães de companhia',
    origin: 'México',
    summaryPt:
      'A raça mais pequena do mundo. Coragem e atitude desproporcionadas ao tamanho. Vocaliza muito.',
    size: 'small',
    weightMinKg: 1.5,
    weightMaxKg: 3,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 18,
    coatLength: 'short',
    shedding: 2,
    hypoallergenic: false,
    energyLevel: 3,
    exerciseDailyMin: 30,
    trainability: 3,
    barkLevel: 'high',
    groomingLevel: 2,
    goodWithKids: 2,
    goodWithDogs: 3,
    goodWithStrangers: 2,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 1,
    heatTolerance: 4,
  },
  {
    nameSlug: 'cocker-spaniel-ingles',
    namePt: 'Cocker Spaniel Inglês',
    fciGroup: 'Grupo 8 — Cães de cobro, levantadores e de água',
    origin: 'Reino Unido',
    summaryPt:
      'Médio, alegre e amigável. Pelagem que requer manutenção. Bom companheiro de família.',
    size: 'medium',
    weightMinKg: 12,
    weightMaxKg: 16,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 15,
    coatLength: 'long',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 60,
    trainability: 4,
    barkLevel: 'medium',
    groomingLevel: 4,
    goodWithKids: 5,
    goodWithDogs: 4,
    goodWithStrangers: 4,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 3,
    heatTolerance: 3,
  },
  {
    nameSlug: 'dalmata',
    namePt: 'Dálmata',
    fciGroup: 'Grupo 6 — Cães de corrida e farejadores',
    origin: 'Croácia',
    summaryPt:
      'Raça atlética com manchas características. Necessita muito exercício diário. Sociável mas reservado com estranhos.',
    size: 'large',
    weightMinKg: 20,
    weightMaxKg: 32,
    lifespanMinYrs: 11,
    lifespanMaxYrs: 13,
    coatLength: 'short',
    shedding: 5,
    hypoallergenic: false,
    energyLevel: 5,
    exerciseDailyMin: 90,
    trainability: 4,
    barkLevel: 'medium',
    groomingLevel: 2,
    goodWithKids: 4,
    goodWithDogs: 3,
    goodWithStrangers: 3,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 3,
    coldTolerance: 3,
    heatTolerance: 3,
  },
  {
    nameSlug: 'dachshund',
    namePt: 'Dachshund (Cão Salsicha)',
    fciGroup: 'Grupo 4 — Dachshunds',
    origin: 'Alemanha',
    summaryPt:
      'Pequeno, alongado e tenaz. Caçador originalmente. Vocaliza e tem tendência a problemas de coluna.',
    size: 'small',
    weightMinKg: 4,
    weightMaxKg: 9,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 16,
    coatLength: 'short',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 3,
    exerciseDailyMin: 45,
    trainability: 3,
    barkLevel: 'high',
    groomingLevel: 2,
    goodWithKids: 3,
    goodWithDogs: 3,
    goodWithStrangers: 3,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 2,
    heatTolerance: 3,
  },
  {
    nameSlug: 'doberman',
    namePt: 'Doberman',
    fciGroup: 'Grupo 2 — Pinscher, Schnauzer, Molossos',
    origin: 'Alemanha',
    summaryPt:
      'Atlético, leal e altamente treinável. Excelente cão de guarda para donos experientes e activos.',
    size: 'large',
    weightMinKg: 27,
    weightMaxKg: 45,
    lifespanMinYrs: 10,
    lifespanMaxYrs: 13,
    coatLength: 'short',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 5,
    exerciseDailyMin: 90,
    trainability: 5,
    barkLevel: 'medium',
    groomingLevel: 1,
    goodWithKids: 4,
    goodWithDogs: 3,
    goodWithStrangers: 2,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 3,
    coldTolerance: 2,
    heatTolerance: 3,
  },
  {
    nameSlug: 'galgo-portugues',
    namePt: 'Podengo Português',
    fciGroup: 'Grupo 5 — Spitz e tipo primitivo',
    origin: 'Portugal',
    summaryPt:
      'Raça portuguesa antiga, ágil e independente. Existe em três tamanhos. Excelente caçador.',
    size: 'medium',
    weightMinKg: 5,
    weightMaxKg: 30,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 15,
    coatLength: 'short',
    shedding: 2,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 60,
    trainability: 3,
    barkLevel: 'medium',
    groomingLevel: 1,
    goodWithKids: 4,
    goodWithDogs: 4,
    goodWithStrangers: 3,
    apartmentFriendly: false,
    noviceFriendly: true,
    toleratesAlone: 3,
    coldTolerance: 3,
    heatTolerance: 4,
  },
  {
    nameSlug: 'golden-retriever',
    namePt: 'Golden Retriever',
    fciGroup: 'Grupo 8 — Cães de cobro, levantadores e de água',
    origin: 'Reino Unido',
    summaryPt:
      'Um dos cães de família mais populares do mundo. Amigável, paciente e treinável. Necessita exercício e companhia.',
    size: 'large',
    weightMinKg: 25,
    weightMaxKg: 34,
    lifespanMinYrs: 10,
    lifespanMaxYrs: 12,
    coatLength: 'long',
    shedding: 5,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 60,
    trainability: 5,
    barkLevel: 'medium',
    groomingLevel: 4,
    goodWithKids: 5,
    goodWithDogs: 5,
    goodWithStrangers: 5,
    apartmentFriendly: false,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 4,
    heatTolerance: 3,
  },
  {
    nameSlug: 'husky-siberiano',
    namePt: 'Husky Siberiano',
    fciGroup: 'Grupo 5 — Spitz e tipo primitivo',
    origin: 'Sibéria',
    summaryPt:
      'Cão de trenó com energia altíssima. Pelagem densa, sofre com calor. Independente e fugitivo se aborrecido.',
    size: 'large',
    weightMinKg: 16,
    weightMaxKg: 27,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 14,
    coatLength: 'medium',
    shedding: 5,
    hypoallergenic: false,
    energyLevel: 5,
    exerciseDailyMin: 120,
    trainability: 2,
    barkLevel: 'medium',
    groomingLevel: 4,
    goodWithKids: 4,
    goodWithDogs: 4,
    goodWithStrangers: 4,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 2,
    coldTolerance: 5,
    heatTolerance: 1,
  },
  {
    nameSlug: 'jack-russell-terrier',
    namePt: 'Jack Russell Terrier',
    fciGroup: 'Grupo 3 — Terriers',
    origin: 'Inglaterra',
    summaryPt:
      'Pequeno terrier cheio de energia e personalidade. Caçador nato, vocaliza e precisa de muito estímulo.',
    size: 'small',
    weightMinKg: 5,
    weightMaxKg: 8,
    lifespanMinYrs: 13,
    lifespanMaxYrs: 16,
    coatLength: 'short',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 5,
    exerciseDailyMin: 60,
    trainability: 4,
    barkLevel: 'high',
    groomingLevel: 2,
    goodWithKids: 3,
    goodWithDogs: 3,
    goodWithStrangers: 3,
    apartmentFriendly: true,
    noviceFriendly: false,
    toleratesAlone: 2,
    coldTolerance: 3,
    heatTolerance: 3,
  },
  {
    nameSlug: 'labrador-retriever',
    namePt: 'Labrador Retriever',
    fciGroup: 'Grupo 8 — Cães de cobro, levantadores e de água',
    origin: 'Canadá',
    summaryPt:
      'Cão de família por excelência. Amigável, brincalhão e treinável. Alta tendência a sobrepeso se sedentário.',
    size: 'large',
    weightMinKg: 25,
    weightMaxKg: 36,
    lifespanMinYrs: 10,
    lifespanMaxYrs: 12,
    coatLength: 'short',
    shedding: 5,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 60,
    trainability: 5,
    barkLevel: 'medium',
    groomingLevel: 2,
    goodWithKids: 5,
    goodWithDogs: 5,
    goodWithStrangers: 5,
    apartmentFriendly: false,
    noviceFriendly: true,
    toleratesAlone: 3,
    coldTolerance: 4,
    heatTolerance: 3,
  },
  {
    nameSlug: 'lulu-da-pomerania',
    namePt: 'Lulu da Pomerânia',
    fciGroup: 'Grupo 5 — Spitz e tipo primitivo',
    origin: 'Alemanha',
    summaryPt:
      'Pequeno spitz com pelagem fofa. Vivaz, vocal e protector. Adequado para apartamento.',
    size: 'small',
    weightMinKg: 1.5,
    weightMaxKg: 3.5,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 16,
    coatLength: 'long',
    shedding: 4,
    hypoallergenic: false,
    energyLevel: 3,
    exerciseDailyMin: 30,
    trainability: 3,
    barkLevel: 'high',
    groomingLevel: 4,
    goodWithKids: 2,
    goodWithDogs: 3,
    goodWithStrangers: 2,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 4,
    heatTolerance: 2,
  },
  {
    nameSlug: 'mastim-napolitano',
    namePt: 'Mastim Napolitano',
    fciGroup: 'Grupo 2 — Pinscher, Schnauzer, Molossos',
    origin: 'Itália',
    summaryPt:
      'Molosso gigante e imponente. Calmo em casa, excelente guardador. Pede dono experiente e espaço.',
    size: 'giant',
    weightMinKg: 50,
    weightMaxKg: 70,
    lifespanMinYrs: 7,
    lifespanMaxYrs: 9,
    coatLength: 'short',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 2,
    exerciseDailyMin: 45,
    trainability: 3,
    barkLevel: 'low',
    groomingLevel: 2,
    goodWithKids: 3,
    goodWithDogs: 2,
    goodWithStrangers: 1,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 4,
    coldTolerance: 3,
    heatTolerance: 2,
  },
  {
    nameSlug: 'pastor-alemao',
    namePt: 'Pastor Alemão',
    fciGroup: 'Grupo 1 — Cães de pastor e boieiros',
    origin: 'Alemanha',
    summaryPt:
      'Versátil, treinável e leal. Usado em trabalho policial e militar. Necessita estímulo mental e exercício.',
    size: 'large',
    weightMinKg: 22,
    weightMaxKg: 40,
    lifespanMinYrs: 9,
    lifespanMaxYrs: 13,
    coatLength: 'medium',
    shedding: 5,
    hypoallergenic: false,
    energyLevel: 5,
    exerciseDailyMin: 90,
    trainability: 5,
    barkLevel: 'medium',
    groomingLevel: 3,
    goodWithKids: 5,
    goodWithDogs: 4,
    goodWithStrangers: 3,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 3,
    coldTolerance: 4,
    heatTolerance: 3,
  },
  {
    nameSlug: 'pastor-australiano',
    namePt: 'Pastor Australiano',
    fciGroup: 'Grupo 1 — Cães de pastor e boieiros',
    origin: 'EUA',
    summaryPt:
      'Cão de pastor enérgico e inteligente. Pelagem média colorida. Pede trabalho diário ou desporto canino.',
    size: 'medium',
    weightMinKg: 16,
    weightMaxKg: 32,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 15,
    coatLength: 'medium',
    shedding: 4,
    hypoallergenic: false,
    energyLevel: 5,
    exerciseDailyMin: 90,
    trainability: 5,
    barkLevel: 'medium',
    groomingLevel: 3,
    goodWithKids: 5,
    goodWithDogs: 4,
    goodWithStrangers: 3,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 2,
    coldTolerance: 4,
    heatTolerance: 3,
  },
  {
    nameSlug: 'pequenino-papillon',
    namePt: 'Papillon',
    fciGroup: 'Grupo 9 — Cães de companhia',
    origin: 'França/Bélgica',
    summaryPt:
      'Pequeno spaniel com orelhas em borboleta. Vivaz, inteligente e treinável. Surpreende em desportos caninos.',
    size: 'small',
    weightMinKg: 3,
    weightMaxKg: 5,
    lifespanMinYrs: 13,
    lifespanMaxYrs: 16,
    coatLength: 'long',
    shedding: 2,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 45,
    trainability: 5,
    barkLevel: 'medium',
    groomingLevel: 3,
    goodWithKids: 3,
    goodWithDogs: 4,
    goodWithStrangers: 3,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 3,
    coldTolerance: 2,
    heatTolerance: 3,
  },
  {
    nameSlug: 'pinscher-miniatura',
    namePt: 'Pinscher Miniatura',
    fciGroup: 'Grupo 2 — Pinscher, Schnauzer, Molossos',
    origin: 'Alemanha',
    summaryPt:
      'Pequeno e cheio de energia. Atrevido apesar do tamanho. Vocaliza e adora estar activo.',
    size: 'small',
    weightMinKg: 4,
    weightMaxKg: 6,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 16,
    coatLength: 'short',
    shedding: 2,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 45,
    trainability: 3,
    barkLevel: 'high',
    groomingLevel: 1,
    goodWithKids: 3,
    goodWithDogs: 3,
    goodWithStrangers: 3,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 2,
    heatTolerance: 3,
  },
  {
    nameSlug: 'poodle-medio',
    namePt: 'Caniche (Poodle)',
    fciGroup: 'Grupo 9 — Cães de companhia',
    origin: 'França',
    summaryPt:
      'Inteligente e elegante, em vários tamanhos (toy, miniatura, médio, grande). Pelagem encaracolada, baixa queda.',
    size: 'medium',
    weightMinKg: 3,
    weightMaxKg: 30,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 15,
    coatLength: 'long',
    shedding: 1,
    hypoallergenic: true,
    energyLevel: 4,
    exerciseDailyMin: 60,
    trainability: 5,
    barkLevel: 'medium',
    groomingLevel: 5,
    goodWithKids: 5,
    goodWithDogs: 4,
    goodWithStrangers: 4,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 3,
    heatTolerance: 3,
  },
  {
    nameSlug: 'pug',
    namePt: 'Pug (Carlin)',
    fciGroup: 'Grupo 9 — Cães de companhia',
    origin: 'China',
    summaryPt:
      'Pequeno braquicéfalo afectuoso e brincalhão. Sensível ao calor pela morfologia da face.',
    size: 'small',
    weightMinKg: 6,
    weightMaxKg: 9,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 15,
    coatLength: 'short',
    shedding: 4,
    hypoallergenic: false,
    energyLevel: 2,
    exerciseDailyMin: 30,
    trainability: 3,
    barkLevel: 'low',
    groomingLevel: 2,
    goodWithKids: 5,
    goodWithDogs: 4,
    goodWithStrangers: 4,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 2,
    heatTolerance: 1,
  },
  {
    nameSlug: 'rafeiro-do-alentejo',
    namePt: 'Rafeiro do Alentejo',
    fciGroup: 'Grupo 2 — Pinscher, Schnauzer, Molossos',
    origin: 'Portugal',
    summaryPt:
      'Raça portuguesa, grande cão de gado. Calmo, territorial e protector. Pede experiência e espaço amplo.',
    size: 'giant',
    weightMinKg: 35,
    weightMaxKg: 55,
    lifespanMinYrs: 10,
    lifespanMaxYrs: 14,
    coatLength: 'medium',
    shedding: 4,
    hypoallergenic: false,
    energyLevel: 2,
    exerciseDailyMin: 60,
    trainability: 3,
    barkLevel: 'medium',
    groomingLevel: 2,
    goodWithKids: 4,
    goodWithDogs: 3,
    goodWithStrangers: 1,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 4,
    coldTolerance: 4,
    heatTolerance: 3,
  },
  {
    nameSlug: 'rottweiler',
    namePt: 'Rottweiler',
    fciGroup: 'Grupo 2 — Pinscher, Schnauzer, Molossos',
    origin: 'Alemanha',
    summaryPt:
      'Robusto, leal e protector. Treinável mas precisa de socialização desde cedo e dono firme.',
    size: 'large',
    weightMinKg: 35,
    weightMaxKg: 60,
    lifespanMinYrs: 8,
    lifespanMaxYrs: 11,
    coatLength: 'short',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 60,
    trainability: 4,
    barkLevel: 'medium',
    groomingLevel: 2,
    goodWithKids: 4,
    goodWithDogs: 2,
    goodWithStrangers: 2,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 3,
    coldTolerance: 3,
    heatTolerance: 3,
  },
  {
    nameSlug: 'samoiedo',
    namePt: 'Samoiedo',
    fciGroup: 'Grupo 5 — Spitz e tipo primitivo',
    origin: 'Sibéria',
    summaryPt: 'Branco e sorridente. Pelagem densa, sofre com calor. Sociável e brincalhão.',
    size: 'large',
    weightMinKg: 16,
    weightMaxKg: 30,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 14,
    coatLength: 'long',
    shedding: 5,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 75,
    trainability: 3,
    barkLevel: 'high',
    groomingLevel: 5,
    goodWithKids: 5,
    goodWithDogs: 4,
    goodWithStrangers: 4,
    apartmentFriendly: false,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 5,
    heatTolerance: 1,
  },
  {
    nameSlug: 'sao-bernardo',
    namePt: 'São Bernardo',
    fciGroup: 'Grupo 2 — Pinscher, Schnauzer, Molossos',
    origin: 'Suíça',
    summaryPt:
      'Gigante gentil, conhecido como cão de salvamento alpino. Calmo e bom com crianças. Esperança de vida curta.',
    size: 'giant',
    weightMinKg: 60,
    weightMaxKg: 90,
    lifespanMinYrs: 8,
    lifespanMaxYrs: 10,
    coatLength: 'long',
    shedding: 4,
    hypoallergenic: false,
    energyLevel: 2,
    exerciseDailyMin: 60,
    trainability: 3,
    barkLevel: 'low',
    groomingLevel: 4,
    goodWithKids: 5,
    goodWithDogs: 4,
    goodWithStrangers: 4,
    apartmentFriendly: false,
    noviceFriendly: true,
    toleratesAlone: 3,
    coldTolerance: 5,
    heatTolerance: 1,
  },
  {
    nameSlug: 'schnauzer-miniatura',
    namePt: 'Schnauzer Miniatura',
    fciGroup: 'Grupo 2 — Pinscher, Schnauzer, Molossos',
    origin: 'Alemanha',
    summaryPt:
      'Pequeno cão robusto com barba característica. Pelagem de baixa queda. Alerta e brincalhão.',
    size: 'small',
    weightMinKg: 5,
    weightMaxKg: 9,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 15,
    coatLength: 'medium',
    shedding: 1,
    hypoallergenic: true,
    energyLevel: 4,
    exerciseDailyMin: 45,
    trainability: 4,
    barkLevel: 'high',
    groomingLevel: 4,
    goodWithKids: 4,
    goodWithDogs: 3,
    goodWithStrangers: 3,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 3,
    heatTolerance: 3,
  },
  {
    nameSlug: 'shar-pei',
    namePt: 'Shar-Pei',
    fciGroup: 'Grupo 2 — Pinscher, Schnauzer, Molossos',
    origin: 'China',
    summaryPt:
      'Reconhecível pelas pregas. Calmo, leal e independente. Cuidados especiais com pele e olhos.',
    size: 'medium',
    weightMinKg: 18,
    weightMaxKg: 30,
    lifespanMinYrs: 8,
    lifespanMaxYrs: 12,
    coatLength: 'short',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 2,
    exerciseDailyMin: 45,
    trainability: 3,
    barkLevel: 'low',
    groomingLevel: 2,
    goodWithKids: 3,
    goodWithDogs: 2,
    goodWithStrangers: 2,
    apartmentFriendly: true,
    noviceFriendly: false,
    toleratesAlone: 4,
    coldTolerance: 3,
    heatTolerance: 2,
  },
  {
    nameSlug: 'shiba-inu',
    namePt: 'Shiba Inu',
    fciGroup: 'Grupo 5 — Spitz e tipo primitivo',
    origin: 'Japão',
    summaryPt:
      'Spitz japonês de tamanho médio. Independente, limpo (lambe-se como um gato) e reservado com estranhos.',
    size: 'medium',
    weightMinKg: 8,
    weightMaxKg: 11,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 16,
    coatLength: 'medium',
    shedding: 4,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 60,
    trainability: 2,
    barkLevel: 'medium',
    groomingLevel: 3,
    goodWithKids: 3,
    goodWithDogs: 2,
    goodWithStrangers: 2,
    apartmentFriendly: true,
    noviceFriendly: false,
    toleratesAlone: 4,
    coldTolerance: 4,
    heatTolerance: 3,
  },
  {
    nameSlug: 'shih-tzu',
    namePt: 'Shih Tzu',
    fciGroup: 'Grupo 9 — Cães de companhia',
    origin: 'Tibete',
    summaryPt:
      'Pequeno cão de companhia com pelagem longa. Afectuoso e adapta-se a apartamento. Pelagem requer cuidados.',
    size: 'small',
    weightMinKg: 4,
    weightMaxKg: 7,
    lifespanMinYrs: 10,
    lifespanMaxYrs: 16,
    coatLength: 'long',
    shedding: 1,
    hypoallergenic: true,
    energyLevel: 2,
    exerciseDailyMin: 30,
    trainability: 3,
    barkLevel: 'low',
    groomingLevel: 5,
    goodWithKids: 4,
    goodWithDogs: 4,
    goodWithStrangers: 4,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 3,
    coldTolerance: 3,
    heatTolerance: 2,
  },
  {
    nameSlug: 'staffordshire-bull-terrier',
    namePt: 'Staffordshire Bull Terrier',
    fciGroup: 'Grupo 3 — Terriers',
    origin: 'Inglaterra',
    summaryPt:
      'Musculado e afectuoso, conhecido como "babysitter". Excelente com crianças. Pede socialização.',
    size: 'medium',
    weightMinKg: 11,
    weightMaxKg: 17,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 14,
    coatLength: 'short',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 4,
    exerciseDailyMin: 60,
    trainability: 4,
    barkLevel: 'medium',
    groomingLevel: 1,
    goodWithKids: 5,
    goodWithDogs: 2,
    goodWithStrangers: 3,
    apartmentFriendly: true,
    noviceFriendly: false,
    toleratesAlone: 3,
    coldTolerance: 3,
    heatTolerance: 3,
  },
  {
    nameSlug: 'weimaraner',
    namePt: 'Weimaraner',
    fciGroup: 'Grupo 7 — Cães de mostra',
    origin: 'Alemanha',
    summaryPt:
      'Cão de caça atlético com pelagem prateada. Energia alta e necessidade de companhia constante.',
    size: 'large',
    weightMinKg: 25,
    weightMaxKg: 40,
    lifespanMinYrs: 10,
    lifespanMaxYrs: 13,
    coatLength: 'short',
    shedding: 3,
    hypoallergenic: false,
    energyLevel: 5,
    exerciseDailyMin: 90,
    trainability: 4,
    barkLevel: 'medium',
    groomingLevel: 1,
    goodWithKids: 4,
    goodWithDogs: 3,
    goodWithStrangers: 3,
    apartmentFriendly: false,
    noviceFriendly: false,
    toleratesAlone: 1,
    coldTolerance: 2,
    heatTolerance: 3,
  },
  {
    nameSlug: 'yorkshire-terrier',
    namePt: 'Yorkshire Terrier',
    fciGroup: 'Grupo 3 — Terriers',
    origin: 'Inglaterra',
    summaryPt:
      'Pequeno e elegante terrier com pelagem longa e sedosa. Atrevido e vocal. Adequado a apartamento.',
    size: 'small',
    weightMinKg: 2,
    weightMaxKg: 3.5,
    lifespanMinYrs: 12,
    lifespanMaxYrs: 16,
    coatLength: 'long',
    shedding: 1,
    hypoallergenic: true,
    energyLevel: 3,
    exerciseDailyMin: 30,
    trainability: 3,
    barkLevel: 'high',
    groomingLevel: 5,
    goodWithKids: 3,
    goodWithDogs: 3,
    goodWithStrangers: 3,
    apartmentFriendly: true,
    noviceFriendly: true,
    toleratesAlone: 2,
    coldTolerance: 2,
    heatTolerance: 3,
  },
]

// ─── Imagens das raças ──────────────────────────────────────────────
//
// URLs estáveis do CDN do projecto Dog CEO (https://dog.ceo/dog-api/),
// público e gratuito. Foram fixadas (não geradas em runtime) para o
// resultado ser determinístico e o seed idempotente.
//
// As 4 raças autóctones portuguesas (Estrela, Cão de Água, Podengo,
// Rafeiro) não estão cobertas pelo Dog CEO. Ficam com `null` e o
// frontend mostra um placeholder. A adicionar manualmente quando
// tivermos imagens próprias com licença clara.

const BREED_IMAGES: Record<string, string | null> = {
  'akita-inu': 'https://images.dog.ceo/breeds/akita/Akita_inu_blanc.jpg',
  beagle: 'https://images.dog.ceo/breeds/beagle/n02088364_17553.jpg',
  'bichon-maltes': 'https://images.dog.ceo/breeds/maltese/n02085936_352.jpg',
  'border-collie': 'https://images.dog.ceo/breeds/collie-border/n02106166_6545.jpg',
  boxer: 'https://images.dog.ceo/breeds/boxer/n02108089_625.jpg',
  'bulldog-frances': 'https://images.dog.ceo/breeds/bulldog-french/n02108915_4214.jpg',
  'bulldog-ingles': 'https://images.dog.ceo/breeds/bulldog-english/jager-1.jpg',
  'cao-da-serra-da-estrela': null,
  'cao-de-agua-portugues': null,
  'cavalier-king-charles': 'https://images.dog.ceo/breeds/spaniel-blenheim/n02086646_2725.jpg',
  chihuahua: 'https://images.dog.ceo/breeds/chihuahua/n02085620_4919.jpg',
  'cocker-spaniel-ingles': 'https://images.dog.ceo/breeds/spaniel-cocker/n02102318_10226.jpg',
  dalmata: 'https://images.dog.ceo/breeds/dalmatian/cooper2.jpg',
  dachshund: 'https://images.dog.ceo/breeds/dachshund/dog-1018408_640.jpg',
  doberman: 'https://images.dog.ceo/breeds/doberman/n02107142_788.jpg',
  'galgo-portugues': null, // Podengo Português — sem imagem em dog.ceo
  'golden-retriever': 'https://images.dog.ceo/breeds/retriever-golden/n02099601_3666.jpg',
  'husky-siberiano': 'https://images.dog.ceo/breeds/husky/n02110185_4115.jpg',
  'jack-russell-terrier': 'https://images.dog.ceo/breeds/terrier-russell/jack-koda-2.jpg',
  'labrador-retriever': 'https://images.dog.ceo/breeds/labrador/n02099712_4403.jpg',
  'lulu-da-pomerania': 'https://images.dog.ceo/breeds/pomeranian/n02112018_6832.jpg',
  'mastim-napolitano': 'https://images.dog.ceo/breeds/mastiff-english/2.jpg',
  'pastor-alemao': 'https://images.dog.ceo/breeds/german-shepherd/n02106662_13123.jpg',
  'pastor-australiano': 'https://images.dog.ceo/breeds/australian-shepherd/pepper2.jpg',
  'pequenino-papillon': 'https://images.dog.ceo/breeds/papillon/n02086910_2380.jpg',
  'pinscher-miniatura': 'https://images.dog.ceo/breeds/pinscher-miniature/n02107312_2893.jpg',
  'poodle-medio': 'https://images.dog.ceo/breeds/poodle-medium/PXL_20210220_100624962.jpg',
  pug: 'https://images.dog.ceo/breeds/pug/n02110958_9642.jpg',
  'rafeiro-do-alentejo': null,
  rottweiler: 'https://images.dog.ceo/breeds/rottweiler/n02106550_4254.jpg',
  samoiedo: 'https://images.dog.ceo/breeds/samoyed/n02111889_6622.jpg',
  'sao-bernardo': 'https://images.dog.ceo/breeds/stbernard/n02109525_523.jpg',
  'schnauzer-miniatura': 'https://images.dog.ceo/breeds/schnauzer-miniature/n02097047_1545.jpg',
  'shar-pei': 'https://images.dog.ceo/breeds/sharpei/noel.jpg',
  'shiba-inu': 'https://images.dog.ceo/breeds/shiba/shiba_20.jpg',
  'shih-tzu': 'https://images.dog.ceo/breeds/shihtzu/n02086240_963.jpg',
  'staffordshire-bull-terrier':
    'https://images.dog.ceo/breeds/bullterrier-staffordshire/n02093256_5646.jpg',
  weimaraner: 'https://images.dog.ceo/breeds/weimaraner/n02092339_7224.jpg',
  'yorkshire-terrier': 'https://images.dog.ceo/breeds/terrier-yorkshire/n02094433_3881.jpg',
}

// Aplica as imagens uma única vez no carregamento do módulo.
for (const breed of BREEDS) {
  if (breed.imageUrl == null) {
    breed.imageUrl = BREED_IMAGES[breed.nameSlug] ?? null
  }
}
